// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
//
// Derived from icons/legacy-aliases.json. Edit that file, not this one.
//
// This map is one-directional and non-transitive: it resolves *legacy* names to
// Phosphor glyphs. It is consulted ONLY after a lookup against the Phosphor
// catalog misses, so a legacy name can never shadow a real Phosphor icon.

export const LEGACY_ALIASES: Readonly<Record<string, string>> = Object.freeze({
  "add": "plus",
  "attachment": "paperclip",
  "bell": "bell",
  "bookmark": "bookmark",
  "calendar": "calendar",
  "check": "check",
  "chevron-down": "caret-down",
  "chevron-left": "caret-left",
  "chevron-right": "caret-right",
  "chevron-up": "caret-up",
  "clock": "clock",
  "close": "x",
  "copy": "copy",
  "document": "file-text",
  "dots-horizontal": "dots-three",
  "dots-vertical": "dots-three-vertical",
  "emoji": "smiley",
  "filter": "funnel",
  "help": "question",
  "home": "house",
  "info": "info",
  "layout-masonry": "squares-four",
  "list": "list-dashes",
  "menu": "list",
  "minus": "minus",
  "pin": "map-pin-simple-line",
  "search": "magnifying-glass",
  "send": "paper-plane-tilt",
  "settings": "gear",
  "sign-in": "sign-in",
  "sign-out": "sign-out",
  "star": "star",
  "success": "check-circle",
  "support": "headset",
  "user": "user",
  "warning-circle": "warning-circle",
  "warning-triangle": "warning"
});

/**
 * Legacy names that collide with a different canonical Phosphor icon.
 * `<al-icon-list>` renders the legacy bulleted list; `<al-icon name="list">`
 * renders the Phosphor hamburger. Intentional — see AGENTS.md > Icon system.
 */
export const SHADOWED_LEGACY_NAMES: readonly string[] = ["list"];
