// Reads libs/al-web-components/schemas/*.schema.json — one per component,
// generated by scripts/generate-component-schemas.js from the CEM. Also
// embeds each component's migration state (`altitude.migration`), so
// altitude_get_component can source it straight from the schema.

import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { PATHS, HINTS, requireFile } from './paths.mjs';

export function loadSchema(tag) {
  requireFile(PATHS.schemasDir, HINTS.cem);
  const file = join(PATHS.schemasDir, `${tag}.schema.json`);
  if (!existsSync(file)) return null;
  return JSON.parse(readFileSync(file, 'utf8'));
}

export function listSchemaTags() {
  requireFile(PATHS.schemasDir, HINTS.cem);
  return readdirSync(PATHS.schemasDir)
    .filter((f) => f.endsWith('.schema.json'))
    .map((f) => f.replace(/\.schema\.json$/, ''));
}
