#!/usr/bin/env node
/**
 * Altitude icon generator — Phosphor edition.
 *
 * Reads the full regular-weight Phosphor set from the `@phosphor-icons/core`
 * devDependency and emits everything the icon system needs. Nothing here is
 * hand-authored except `legacy-aliases.json`.
 *
 * Emits (all under components/icon/):
 *   phosphor/<name>.ts   1,512 glyph data modules (tree-shakeable, /*#__PURE__* /)
 *   glyphs.ts            named-export barrel — the recommended consumer entry point
 *   lazy.ts              opt-in loader map for <al-icon name> with no explicit import
 *   catalog.ts           name/tags/categories metadata — Storybook browse + search
 *   all.ts               every glyph, eagerly registered — Storybook catalog only
 *   icon-aliases.ts      derived from legacy-aliases.json
 *   icons/<legacy>.ts    37 deprecated per-glyph elements, repointed at Phosphor
 *
 * Deliberately does NOT:
 *   - write anything into libs/al-react (the old generator did; the package
 *     boundary is now real)
 *   - build a webfont (removed — 1,512 glyphs base64-inlined was ~275-400 KB)
 *
 * Glyph modules are emitted OUTSIDE components/icon/icons/ on purpose:
 * vite.config.mjs `findIconEntries()` globs that directory and turns every file
 * into a Rollup entry. Putting 1,512 glyphs there would create 1,512 entries.
 */

import { createRequire } from 'node:module';
import { readFile, writeFile, mkdir, rm, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = path.join(__dirname, '..');
const ICON_DIR = path.join(PKG_ROOT, 'components', 'icon');
const GLYPH_DIR = path.join(ICON_DIR, 'phosphor');
const SHIM_DIR = path.join(ICON_DIR, 'icons');
const LEGACY_SVG_DIR = path.join(ICON_DIR, 'svgs');

const WEIGHT = 'regular';
const EXPECTED_COUNT = 1512;
const VIEW_BOX = '0 0 256 256';
const WRITE_CONCURRENCY = 64;

const BANNER = '// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.';

/* ------------------------------------------------------------------ utils */

const RESERVED = new Set(
  ('break case catch class const continue debugger default delete do else enum export extends false ' +
    'finally for function if implements import in instanceof interface let new null package private ' +
    'protected public return static super switch this throw true try typeof var void while with yield await')
    .split(' ')
);

const toCamel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const toPascal = (s) => s.replace(/(^[a-z0-9]|-[a-z0-9])/g, (m) => m.replace('-', '').toUpperCase());

/** Barrel export identifier. Three Phosphor names (`export`, `function`, `package`) are reserved words. */
function toExportName(kebab) {
  const camel = toCamel(kebab);
  return RESERVED.has(camel) ? `${camel}Icon` : camel;
}

/** Run `fn` over `items` with at most `limit` in flight. 1,512 unbounded writes exhausts FDs on Windows. */
async function mapLimit(items, limit, fn) {
  const out = new Array(items.length);
  let cursor = 0;
  const worker = async () => {
    for (;;) {
      const i = cursor++;
      if (i >= items.length) return;
      out[i] = await fn(items[i], i);
    }
  };
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
  return out;
}

function fail(msg) {
  console.error(`\n[icons] ${msg}\n`);
  process.exit(1);
}

/* ------------------------------------------------- stage 1: resolve source */

function resolvePhosphorRoot() {
  // Must resolve through Node, not a hard-coded path: pnpm puts the real package
  // under node_modules/.pnpm/@phosphor-icons+core@x.y.z/… and does not hoist.
  // The package's `exports` map does not expose ./package.json, so resolve the
  // main entry and walk up to the directory that owns `assets/`.
  const require = createRequire(path.join(__dirname, 'noop.js'));
  let dir;
  try {
    dir = path.dirname(require.resolve('@phosphor-icons/core'));
  } catch {
    fail('cannot resolve @phosphor-icons/core — run `pnpm install` first.');
  }
  for (let i = 0; i < 6 && !existsSync(path.join(dir, 'assets', WEIGHT)); i++) dir = path.dirname(dir);
  if (!existsSync(path.join(dir, 'assets', WEIGHT))) {
    fail(`resolved @phosphor-icons/core but found no assets/${WEIGHT} directory.`);
  }
  return dir;
}

/**
 * Extract the inner markup of a Phosphor asset.
 *
 * Verified across all 1,512 regular assets: exactly one `<svg>` attribute set,
 * exactly one `<path>` child, zero `stroke=` attributes, zero `<rect fill="none">`
 * bounding boxes. The assertions below exist so a future Phosphor release that
 * breaks any of those invariants fails the build loudly instead of silently
 * shipping icons that ignore `--al-icon-fill`.
 */
function extractInner(svgText, name) {
  const body = svgText
    .trim()
    .replace(/^<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .trim();

  if (!body.startsWith('<path')) fail(`${name}: expected a leading <path>, got: ${body.slice(0, 60)}`);
  if (body.includes('stroke=')) {
    fail(`${name}: contains a stroke attribute. icon.scss styles \`fill\` only, so this glyph would ignore --al-icon-fill.`);
  }
  if (body.includes('`') || body.includes('${')) fail(`${name}: markup would break the lit template literal.`);
  return body;
}

/* --------------------------------------------------- stage 2: file emitters */

const glyphModule = (kebab, inner) => `${BANNER}
import { svg } from 'lit';
import type { AltitudeIconDef } from '../types';

/** Phosphor \`${kebab}\` (${WEIGHT}). */
const glyph: AltitudeIconDef = { v: '${VIEW_BOX}', c: /*#__PURE__*/ svg\`${inner}\` };

export default glyph;
`;

const shimModule = (legacy, phosphor) => {
  const cls = `ALIcon${toPascal(legacy)}`;
  const tag = `al-icon-${legacy}`;
  return `${BANNER}
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/${phosphor}';

// Loading this element also makes <al-icon name="${phosphor}"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ '${phosphor}': glyph });

/**
 * Icon: ${tag}
 *
 * @deprecated Use \`<al-icon name="${phosphor}">\`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ${cls} extends ALIconBase {
  static el = '${tag}';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(${cls}.el) === undefined) {
  customElements.define(${cls}.el, ${cls});
}

declare global {
  interface HTMLElementTagNameMap {
    '${tag}': ${cls};
  }
}
`;
};

/* ------------------------------------------------------------------- main */

const phosphorRoot = resolvePhosphorRoot();
const assetDir = path.join(phosphorRoot, WEIGHT === 'regular' ? 'assets/regular' : `assets/${WEIGHT}`);

const require = createRequire(path.join(__dirname, 'noop.js'));
const { icons: catalogRaw } = require(path.join(phosphorRoot, 'dist', 'index.umd.js'));

if (!Array.isArray(catalogRaw)) fail('could not read the Phosphor catalog from dist/index.umd.js');
if (catalogRaw.length !== EXPECTED_COUNT) {
  fail(
    `Phosphor catalog has ${catalogRaw.length} icons, expected ${EXPECTED_COUNT}. ` +
      `A version bump changed the surface area — review, then update EXPECTED_COUNT.`
  );
}

const aliasFile = JSON.parse(await readFile(path.join(__dirname, 'legacy-aliases.json'), 'utf8'));
const aliases = aliasFile.aliases;
const shadowed = aliasFile.shadowed ?? [];

const names = catalogRaw.map((i) => i.name).sort();
const nameSet = new Set(names);

// Validate the hand-authored map before writing anything.
for (const [legacy, def] of Object.entries(aliases)) {
  if (!nameSet.has(def.phosphor)) {
    fail(`legacy-aliases.json: "${legacy}" maps to "${def.phosphor}", which is not a Phosphor ${WEIGHT} icon.`);
  }
}
const renamed = names.filter((n) => toExportName(n) !== toCamel(n));

console.log(`[icons] @phosphor-icons/core @ ${path.relative(PKG_ROOT, phosphorRoot)}`);
console.log(`[icons] ${names.length} ${WEIGHT} glyphs, ${Object.keys(aliases).length} legacy aliases`);
if (renamed.length) {
  console.log(`[icons] reserved-word export renames: ${renamed.map((n) => `${n} -> ${toExportName(n)}`).join(', ')}`);
}
if (shadowed.length) {
  for (const s of shadowed) {
    console.warn(
      `[icons] WARNING: legacy "${s}" is shadowed — <al-icon-${s}> renders ` +
        `"${aliases[s].phosphor}" but <al-icon name="${s}"> renders the Phosphor "${s}". This is intentional.`
    );
  }
}

// Fresh directories. Removing GLYPH_DIR wholesale is how stale glyphs from a
// previous Phosphor version get collected.
await rm(GLYPH_DIR, { recursive: true, force: true });
await mkdir(GLYPH_DIR, { recursive: true });
await mkdir(SHIM_DIR, { recursive: true });

// Read + normalize every asset first, so a bad glyph aborts before any write.
const glyphs = await mapLimit(names, WRITE_CONCURRENCY, async (name) => {
  const raw = await readFile(path.join(assetDir, `${name}.svg`), 'utf8');
  return { name, inner: extractInner(raw, name) };
});

await mapLimit(glyphs, WRITE_CONCURRENCY, ({ name, inner }) =>
  writeFile(path.join(GLYPH_DIR, `${name}.ts`), glyphModule(name, inner), 'utf8')
);

// --- barrel: the recommended, tree-shakeable consumer entry point
await writeFile(
  path.join(ICON_DIR, 'glyphs.ts'),
  `${BANNER}
//
// Tree-shakeable named exports. Import only what you use:
//
//   import { caretDown } from '@southleft/al-web-components/dist/components/icon/glyphs.js';
//   import { registerIcons } from '@southleft/al-web-components/dist/components/icon/registry.js';
//   registerIcons({ 'caret-down': caretDown });
//
${names.map((n) => `export { default as ${toExportName(n)} } from './phosphor/${n}';`).join('\n')}
`,
  'utf8'
);

// --- catalog: metadata for the Storybook browser. Never imported by an app.
await writeFile(
  path.join(ICON_DIR, 'catalog.ts'),
  `${BANNER}
//
// Browse/search metadata for the Storybook catalog. This module is ~180 KB and is
// deliberately NOT reachable from any application entry point.

export interface AltitudeIconCatalogEntry {
  name: string;
  pascalName: string;
  categories: readonly string[];
  tags: readonly string[];
}

export const ICON_CATEGORIES: readonly string[] = ${JSON.stringify(
    [...new Set(catalogRaw.flatMap((i) => i.categories ?? []))].sort()
  )};

export const ICON_NAMES: readonly string[] = ${JSON.stringify(names)};

export const catalog: readonly AltitudeIconCatalogEntry[] = ${JSON.stringify(
    catalogRaw
      .slice()
      .sort((a, b) => a.name.localeCompare(b.name))
      .map((i) => ({
        name: i.name,
        pascalName: i.pascal_name,
        categories: i.categories ?? [],
        tags: i.tags ?? [],
      })),
    null,
    0
  )};
`,
  'utf8'
);

// --- lazy: opt-in resolver. Generated as a literal map rather than
// import.meta.glob so the module stays bundler-agnostic.
await writeFile(
  path.join(ICON_DIR, 'lazy.ts'),
  `${BANNER}
//
// Opt-in dynamic loading for <al-icon name="..."> when the glyph has not been
// registered explicitly. Importing this module costs ~13 KB gzipped (the map
// below) and one network round-trip per icon, and it cannot render under SSR.
//
// Prefer explicit registration via ./glyphs.js. Reach for this in Storybook,
// prototypes, or when icon names come from data you do not control.
//
//   import '@southleft/al-web-components/dist/components/icon/lazy.js';
//
import { setIconResolver } from './registry';
import type { AltitudeIconDef } from './types';

type Loader = () => Promise<{ default: AltitudeIconDef }>;

const LOADERS: Record<string, Loader> = {
${names.map((n) => `  '${n}': () => import('./phosphor/${n}'),`).join('\n')}
};

setIconResolver(async (name) => {
  const load = LOADERS[name];
  if (!load) return undefined;
  return (await load()).default;
});

export const LAZY_ICON_NAMES: readonly string[] = Object.keys(LOADERS);
`,
  'utf8'
);

// --- all: eager registration of every glyph. Storybook catalog only.
await writeFile(
  path.join(ICON_DIR, 'all.ts'),
  `${BANNER}
//
// Registers all ${names.length} glyphs eagerly (~230 KB gzipped). This exists for the
// Storybook catalog page. Do NOT import it from an application.

import { registerIcons } from './registry';
${names.map((n) => `import ${toExportName(n)} from './phosphor/${n}';`).join('\n')}

registerIcons({
${names.map((n) => `  '${n}': ${toExportName(n)},`).join('\n')}
});
`,
  'utf8'
);

// --- aliases: derived from legacy-aliases.json
await writeFile(
  path.join(ICON_DIR, 'icon-aliases.ts'),
  `${BANNER}
//
// Derived from icons/legacy-aliases.json. Edit that file, not this one.
//
// This map is one-directional and non-transitive: it resolves *legacy* names to
// Phosphor glyphs. It is consulted ONLY after a lookup against the Phosphor
// catalog misses, so a legacy name can never shadow a real Phosphor icon.

export const LEGACY_ALIASES: Readonly<Record<string, string>> = Object.freeze(${JSON.stringify(
    Object.fromEntries(Object.entries(aliases).map(([k, v]) => [k, v.phosphor])),
    null,
    2
  )});

/**
 * Legacy names that collide with a different canonical Phosphor icon.
 * \`<al-icon-list>\` renders the legacy bulleted list; \`<al-icon name="list">\`
 * renders the Phosphor hamburger. Intentional — see AGENTS.md > Icon system.
 */
export const SHADOWED_LEGACY_NAMES: readonly string[] = ${JSON.stringify(shadowed)};
`,
  'utf8'
);

// --- legacy per-glyph elements, repointed at Phosphor artwork
const legacyNames = Object.keys(aliases).sort();
await mapLimit(legacyNames, WRITE_CONCURRENCY, (legacy) =>
  writeFile(path.join(SHIM_DIR, `${legacy}.ts`), shimModule(legacy, aliases[legacy].phosphor), 'utf8')
);

// Drop any element module that is no longer in the alias map.
for (const file of await readdir(SHIM_DIR)) {
  if (!file.endsWith('.ts')) continue;
  if (!legacyNames.includes(file.slice(0, -3))) {
    await rm(path.join(SHIM_DIR, file));
    console.log(`[icons] removed stale element module: icons/${file}`);
  }
}

// The old 20x20/24x24 lit templates are dead now that every element points at
// Phosphor. Source SVGs stay in icons/svgs/ as historical reference.
if (existsSync(LEGACY_SVG_DIR)) {
  await rm(LEGACY_SVG_DIR, { recursive: true, force: true });
  console.log('[icons] removed dead components/icon/svgs/');
}

console.log(
  `[icons] done — ${names.length} glyphs, ${legacyNames.length} legacy elements, ` +
    `glyphs.ts / lazy.ts / catalog.ts / all.ts / icon-aliases.ts`
);
