// /llms-components.txt — every element's complete API. Generated by src/lib/artifacts.mjs from the
// same artifacts the pages render: the CEM, the published token layer, the
// committed agent digests and the axe report. Nothing here is hand-maintained.
import type { APIRoute } from 'astro';
import { llmsComponents } from '../lib/artifacts.mjs';
import { DEFAULT_CONTEXT } from '../lib/context.mjs';

export const GET: APIRoute = () =>
  new Response(llmsComponents(DEFAULT_CONTEXT), {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
