// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/plus';

// Loading this element also makes <al-icon name="plus"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'plus': glyph });

/**
 * Icon: al-icon-add
 *
 * @deprecated Use `<al-icon name="plus">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconAdd extends ALIconBase {
  static el = 'al-icon-add';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconAdd.el) === undefined) {
  customElements.define(ALIconAdd.el, ALIconAdd);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-add': ALIconAdd;
  }
}
