// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/paperclip';

// Loading this element also makes <al-icon name="paperclip"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'paperclip': glyph });

/**
 * Icon: al-icon-attachment
 *
 * @deprecated Use `<al-icon name="paperclip">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconAttachment extends ALIconBase {
  static el = 'al-icon-attachment';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconAttachment.el) === undefined) {
  customElements.define(ALIconAttachment.el, ALIconAttachment);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-attachment': ALIconAttachment;
  }
}
