// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/bell';

// Loading this element also makes <al-icon name="bell"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'bell': glyph });

/**
 * Icon: al-icon-bell
 *
 * @deprecated Use `<al-icon name="bell">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconBell extends ALIconBase {
  static el = 'al-icon-bell';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconBell.el) === undefined) {
  customElements.define(ALIconBell.el, ALIconBell);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-bell': ALIconBell;
  }
}
