// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/bookmark';

// Loading this element also makes <al-icon name="bookmark"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'bookmark': glyph });

/**
 * Icon: al-icon-bookmark
 *
 * @deprecated Use `<al-icon name="bookmark">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconBookmark extends ALIconBase {
  static el = 'al-icon-bookmark';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconBookmark.el) === undefined) {
  customElements.define(ALIconBookmark.el, ALIconBookmark);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-bookmark': ALIconBookmark;
  }
}
