// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/calendar';

// Loading this element also makes <al-icon name="calendar"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'calendar': glyph });

/**
 * Icon: al-icon-calendar
 *
 * @deprecated Use `<al-icon name="calendar">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconCalendar extends ALIconBase {
  static el = 'al-icon-calendar';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconCalendar.el) === undefined) {
  customElements.define(ALIconCalendar.el, ALIconCalendar);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-calendar': ALIconCalendar;
  }
}
