// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/check';

// Loading this element also makes <al-icon name="check"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'check': glyph });

/**
 * Icon: al-icon-check
 *
 * @deprecated Use `<al-icon name="check">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconCheck extends ALIconBase {
  static el = 'al-icon-check';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconCheck.el) === undefined) {
  customElements.define(ALIconCheck.el, ALIconCheck);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-check': ALIconCheck;
  }
}
