// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/caret-up';

// Loading this element also makes <al-icon name="caret-up"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'caret-up': glyph });

/**
 * Icon: al-icon-chevron-up
 *
 * @deprecated Use `<al-icon name="caret-up">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconChevronUp extends ALIconBase {
  static el = 'al-icon-chevron-up';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconChevronUp.el) === undefined) {
  customElements.define(ALIconChevronUp.el, ALIconChevronUp);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-chevron-up': ALIconChevronUp;
  }
}
