// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/caret-down';

// Loading this element also makes <al-icon name="caret-down"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'caret-down': glyph });

/**
 * Icon: al-icon-chevron-down
 *
 * @deprecated Use `<al-icon name="caret-down">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconChevronDown extends ALIconBase {
  static el = 'al-icon-chevron-down';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconChevronDown.el) === undefined) {
  customElements.define(ALIconChevronDown.el, ALIconChevronDown);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-chevron-down': ALIconChevronDown;
  }
}
