// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/caret-left';

// Loading this element also makes <al-icon name="caret-left"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'caret-left': glyph });

/**
 * Icon: al-icon-chevron-left
 *
 * @deprecated Use `<al-icon name="caret-left">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconChevronLeft extends ALIconBase {
  static el = 'al-icon-chevron-left';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconChevronLeft.el) === undefined) {
  customElements.define(ALIconChevronLeft.el, ALIconChevronLeft);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-chevron-left': ALIconChevronLeft;
  }
}
