// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/clock';

// Loading this element also makes <al-icon name="clock"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'clock': glyph });

/**
 * Icon: al-icon-clock
 *
 * @deprecated Use `<al-icon name="clock">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconClock extends ALIconBase {
  static el = 'al-icon-clock';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconClock.el) === undefined) {
  customElements.define(ALIconClock.el, ALIconClock);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-clock': ALIconClock;
  }
}
