// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/x';

// Loading this element also makes <al-icon name="x"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'x': glyph });

/**
 * Icon: al-icon-close
 *
 * @deprecated Use `<al-icon name="x">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconClose extends ALIconBase {
  static el = 'al-icon-close';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconClose.el) === undefined) {
  customElements.define(ALIconClose.el, ALIconClose);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-close': ALIconClose;
  }
}
