// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/copy';

// Loading this element also makes <al-icon name="copy"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'copy': glyph });

/**
 * Icon: al-icon-copy
 *
 * @deprecated Use `<al-icon name="copy">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconCopy extends ALIconBase {
  static el = 'al-icon-copy';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconCopy.el) === undefined) {
  customElements.define(ALIconCopy.el, ALIconCopy);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-copy': ALIconCopy;
  }
}
