// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/file-text';

// Loading this element also makes <al-icon name="file-text"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'file-text': glyph });

/**
 * Icon: al-icon-document
 *
 * @deprecated Use `<al-icon name="file-text">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconDocument extends ALIconBase {
  static el = 'al-icon-document';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconDocument.el) === undefined) {
  customElements.define(ALIconDocument.el, ALIconDocument);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-document': ALIconDocument;
  }
}
