// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/dots-three-vertical';

// Loading this element also makes <al-icon name="dots-three-vertical"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'dots-three-vertical': glyph });

/**
 * Icon: al-icon-dots-vertical
 *
 * @deprecated Use `<al-icon name="dots-three-vertical">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconDotsVertical extends ALIconBase {
  static el = 'al-icon-dots-vertical';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconDotsVertical.el) === undefined) {
  customElements.define(ALIconDotsVertical.el, ALIconDotsVertical);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-dots-vertical': ALIconDotsVertical;
  }
}
