// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/dots-three';

// Loading this element also makes <al-icon name="dots-three"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'dots-three': glyph });

/**
 * Icon: al-icon-dots-horizontal
 *
 * @deprecated Use `<al-icon name="dots-three">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconDotsHorizontal extends ALIconBase {
  static el = 'al-icon-dots-horizontal';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconDotsHorizontal.el) === undefined) {
  customElements.define(ALIconDotsHorizontal.el, ALIconDotsHorizontal);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-dots-horizontal': ALIconDotsHorizontal;
  }
}
