// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/question';

// Loading this element also makes <al-icon name="question"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'question': glyph });

/**
 * Icon: al-icon-help
 *
 * @deprecated Use `<al-icon name="question">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconHelp extends ALIconBase {
  static el = 'al-icon-help';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconHelp.el) === undefined) {
  customElements.define(ALIconHelp.el, ALIconHelp);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-help': ALIconHelp;
  }
}
