// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/house';

// Loading this element also makes <al-icon name="house"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'house': glyph });

/**
 * Icon: al-icon-home
 *
 * @deprecated Use `<al-icon name="house">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconHome extends ALIconBase {
  static el = 'al-icon-home';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconHome.el) === undefined) {
  customElements.define(ALIconHome.el, ALIconHome);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-home': ALIconHome;
  }
}
