// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/info';

// Loading this element also makes <al-icon name="info"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'info': glyph });

/**
 * Icon: al-icon-info
 *
 * @deprecated Use `<al-icon name="info">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconInfo extends ALIconBase {
  static el = 'al-icon-info';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconInfo.el) === undefined) {
  customElements.define(ALIconInfo.el, ALIconInfo);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-info': ALIconInfo;
  }
}
