// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/squares-four';

// Loading this element also makes <al-icon name="squares-four"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'squares-four': glyph });

/**
 * Icon: al-icon-layout-masonry
 *
 * @deprecated Use `<al-icon name="squares-four">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconLayoutMasonry extends ALIconBase {
  static el = 'al-icon-layout-masonry';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconLayoutMasonry.el) === undefined) {
  customElements.define(ALIconLayoutMasonry.el, ALIconLayoutMasonry);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-layout-masonry': ALIconLayoutMasonry;
  }
}
