// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/list-dashes';

// Loading this element also makes <al-icon name="list-dashes"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'list-dashes': glyph });

/**
 * Icon: al-icon-list
 *
 * @deprecated Use `<al-icon name="list-dashes">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconList extends ALIconBase {
  static el = 'al-icon-list';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconList.el) === undefined) {
  customElements.define(ALIconList.el, ALIconList);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-list': ALIconList;
  }
}
