// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/list';

// Loading this element also makes <al-icon name="list"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'list': glyph });

/**
 * Icon: al-icon-menu
 *
 * @deprecated Use `<al-icon name="list">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconMenu extends ALIconBase {
  static el = 'al-icon-menu';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconMenu.el) === undefined) {
  customElements.define(ALIconMenu.el, ALIconMenu);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-menu': ALIconMenu;
  }
}
