// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/minus';

// Loading this element also makes <al-icon name="minus"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'minus': glyph });

/**
 * Icon: al-icon-minus
 *
 * @deprecated Use `<al-icon name="minus">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconMinus extends ALIconBase {
  static el = 'al-icon-minus';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconMinus.el) === undefined) {
  customElements.define(ALIconMinus.el, ALIconMinus);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-minus': ALIconMinus;
  }
}
