// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/map-pin-simple-line';

// Loading this element also makes <al-icon name="map-pin-simple-line"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'map-pin-simple-line': glyph });

/**
 * Icon: al-icon-pin
 *
 * @deprecated Use `<al-icon name="map-pin-simple-line">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconPin extends ALIconBase {
  static el = 'al-icon-pin';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconPin.el) === undefined) {
  customElements.define(ALIconPin.el, ALIconPin);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-pin': ALIconPin;
  }
}
