// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/magnifying-glass';

// Loading this element also makes <al-icon name="magnifying-glass"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'magnifying-glass': glyph });

/**
 * Icon: al-icon-search
 *
 * @deprecated Use `<al-icon name="magnifying-glass">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconSearch extends ALIconBase {
  static el = 'al-icon-search';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconSearch.el) === undefined) {
  customElements.define(ALIconSearch.el, ALIconSearch);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-search': ALIconSearch;
  }
}
