// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/paper-plane-tilt';

// Loading this element also makes <al-icon name="paper-plane-tilt"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'paper-plane-tilt': glyph });

/**
 * Icon: al-icon-send
 *
 * @deprecated Use `<al-icon name="paper-plane-tilt">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconSend extends ALIconBase {
  static el = 'al-icon-send';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconSend.el) === undefined) {
  customElements.define(ALIconSend.el, ALIconSend);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-send': ALIconSend;
  }
}
