// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/gear';

// Loading this element also makes <al-icon name="gear"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'gear': glyph });

/**
 * Icon: al-icon-settings
 *
 * @deprecated Use `<al-icon name="gear">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconSettings extends ALIconBase {
  static el = 'al-icon-settings';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconSettings.el) === undefined) {
  customElements.define(ALIconSettings.el, ALIconSettings);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-settings': ALIconSettings;
  }
}
