// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/sign-in';

// Loading this element also makes <al-icon name="sign-in"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'sign-in': glyph });

/**
 * Icon: al-icon-sign-in
 *
 * @deprecated Use `<al-icon name="sign-in">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconSignIn extends ALIconBase {
  static el = 'al-icon-sign-in';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconSignIn.el) === undefined) {
  customElements.define(ALIconSignIn.el, ALIconSignIn);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-sign-in': ALIconSignIn;
  }
}
