// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/sign-out';

// Loading this element also makes <al-icon name="sign-out"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'sign-out': glyph });

/**
 * Icon: al-icon-sign-out
 *
 * @deprecated Use `<al-icon name="sign-out">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconSignOut extends ALIconBase {
  static el = 'al-icon-sign-out';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconSignOut.el) === undefined) {
  customElements.define(ALIconSignOut.el, ALIconSignOut);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-sign-out': ALIconSignOut;
  }
}
