// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/star';

// Loading this element also makes <al-icon name="star"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'star': glyph });

/**
 * Icon: al-icon-star
 *
 * @deprecated Use `<al-icon name="star">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconStar extends ALIconBase {
  static el = 'al-icon-star';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconStar.el) === undefined) {
  customElements.define(ALIconStar.el, ALIconStar);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-star': ALIconStar;
  }
}
