// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/check-circle';

// Loading this element also makes <al-icon name="check-circle"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'check-circle': glyph });

/**
 * Icon: al-icon-success
 *
 * @deprecated Use `<al-icon name="check-circle">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconSuccess extends ALIconBase {
  static el = 'al-icon-success';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconSuccess.el) === undefined) {
  customElements.define(ALIconSuccess.el, ALIconSuccess);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-success': ALIconSuccess;
  }
}
