// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/headset';

// Loading this element also makes <al-icon name="headset"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'headset': glyph });

/**
 * Icon: al-icon-support
 *
 * @deprecated Use `<al-icon name="headset">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconSupport extends ALIconBase {
  static el = 'al-icon-support';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconSupport.el) === undefined) {
  customElements.define(ALIconSupport.el, ALIconSupport);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-support': ALIconSupport;
  }
}
