// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/warning-circle';

// Loading this element also makes <al-icon name="warning-circle"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'warning-circle': glyph });

/**
 * Icon: al-icon-warning-circle
 *
 * @deprecated Use `<al-icon name="warning-circle">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconWarningCircle extends ALIconBase {
  static el = 'al-icon-warning-circle';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconWarningCircle.el) === undefined) {
  customElements.define(ALIconWarningCircle.el, ALIconWarningCircle);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-warning-circle': ALIconWarningCircle;
  }
}
