// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { ALIconBase } from '../icon-base';
import { registerIcons } from '../registry';
import glyph from '../phosphor/warning';

// Loading this element also makes <al-icon name="warning"> resolve without
// the lazy loader — a legacy import is a free registration.
registerIcons({ 'warning': glyph });

/**
 * Icon: al-icon-warning-triangle
 *
 * @deprecated Use `<al-icon name="warning">`. This element is a frozen
 * backwards-compatibility alias and will be removed in the next major version.
 */
export class ALIconWarningTriangle extends ALIconBase {
  static el = 'al-icon-warning-triangle';
  static glyph = glyph;
}

if ((globalThis as any).alAutoRegistry === true && customElements.get(ALIconWarningTriangle.el) === undefined) {
  customElements.define(ALIconWarningTriangle.el, ALIconWarningTriangle);
}

declare global {
  interface HTMLElementTagNameMap {
    'al-icon-warning-triangle': ALIconWarningTriangle;
  }
}
