/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-breadcrumbs.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Breadcrumbs"
 * component set (node 3558:60804).
 *
 * Mapped variant axes: none.
 * Props the contract marks `omit` (no Figma axis): isTruncated, itemsAfterCollapse, itemsBeforeCollapse, menuId.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3558-60804', {
  props: {},
  example: (props) => html`
    <al-breadcrumbs>
      Breadcrumbs
    </al-breadcrumbs>
  `,
});
