/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-badge.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Badge"
 * component set (node 3538:35772).
 *
 * Mapped variant axes: Shape, Variant.
 * Props the contract marks `omit` (no Figma axis): position.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3538-35772', {
  props: {
    isDot: figma.enum('Shape', {
      Dot: true,
    }),
    variant: figma.enum('Variant', {
      Danger: 'danger',
      Info: 'info',
      Success: 'success',
      Warning: 'warning',
    }),
  },
  example: (props) => html`
    <al-badge
      isDot="${props.isDot}"
      variant="${props.variant}"
    >
      Badge
    </al-badge>
  `,
});
