/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-banner.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Banner"
 * component set (node 3570:1351).
 *
 * Mapped variant axes: none.
 * Props the contract marks `omit` (no Figma axis): isDismissed.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for icon, link.
 */
import figma from '@figma/code-connect';
import { ALBanner } from '@southleft/al-react';

figma.connect(ALBanner, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3570-1351', {
  props: {},
  example: (props) => (
    <ALBanner>
      Banner
      <span slot="icon">Icon</span>
      <span slot="link">Link</span>
    </ALBanner>
  ),
});
