/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-breadcrumbs.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Breadcrumbs"
 * component set (node 3558:60804).
 *
 * Mapped variant axes: none.
 * Props the contract marks `omit` (no Figma axis): isTruncated, itemsAfterCollapse, itemsBeforeCollapse, menuId.
 */
import figma from '@figma/code-connect';
import { ALBreadcrumbs } from '@southleft/al-react';

figma.connect(ALBreadcrumbs, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3558-60804', {
  props: {},
  example: (props) => (
    <ALBreadcrumbs>
      Breadcrumbs
    </ALBreadcrumbs>
  ),
});
