/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-button.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Button"
 * component set (node 3538:36730).
 *
 * Mapped variant axes: State, Shape, Size, Variant.
 * Props the contract marks `omit` (no Figma axis): ariaControls, fullWidth, hideText, href, isAriaDisabled, isExpanded, isPressed, name, target, type, value.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for before, after.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3538-36730', {
  props: {
    isDisabled: figma.enum('State', {
      Disabled: true,
    }),
    isPill: figma.enum('Shape', {
      Pill: true,
    }),
    size: figma.enum('Size', {
      Lg: 'lg',
      Sm: 'sm',
    }),
    variant: figma.enum('Variant', {
      Bare: 'bare',
      Secondary: 'secondary',
      Tertiary: 'tertiary',
    }),
  },
  example: (props) => html`
    <al-button
      isDisabled="${props.isDisabled}"
      isPill="${props.isPill}"
      size="${props.size}"
      variant="${props.variant}"
    >
      <span slot="before">Before</span>
      Button
      <span slot="after">After</span>
    </al-button>
  `,
});
