/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-breadcrumbs-item.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Breadcrumbs Item"
 * component set (node 3538:36342).
 *
 * Mapped variant axes: Separator, Current.
 * Props the contract marks `omit` (no Figma axis): href, isTruncated, target.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3538-36342', {
  props: {
    hasSeparator: figma.enum('Separator', {
      Yes: true,
    }),
    isCurrent: figma.enum('Current', {
      Yes: true,
    }),
  },
  example: (props) => html`
    <al-breadcrumbs-item
      hasSeparator="${props.hasSeparator}"
      isCurrent="${props.isCurrent}"
    >
      Breadcrumbs Item
    </al-breadcrumbs-item>
  `,
});
