/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-combobox.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Combobox"
 * component set (node 3558:63019).
 *
 * Mapped variant axes: Label.
 * Props the contract marks `omit` (no Figma axis): align, ariaDescribedBy, errorNote, fieldId, fieldNote, filterMode, isRequired, label, noResultsText, placeholder, selectedValue, value.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for error, field-note.
 */
import figma from '@figma/code-connect';
import { ALCombobox } from '@southleft/al-react';

figma.connect(ALCombobox, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3558-63019', {
  props: {
    hideLabel: figma.enum('Label', {
      Hidden: true,
    }),
  },
  example: (props) => (
    <ALCombobox
      hideLabel={props.hideLabel}
    >
      <span slot="error">Error</span>
      <span slot="field-note">Field note</span>
    </ALCombobox>
  ),
});
