/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-chip.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Chip"
 * component set (node 3540:43526).
 *
 * Mapped variant axes: Shape, Variant.
 * Props the contract marks `omit` (no Figma axis): isDismissed.
 */
import figma from '@figma/code-connect';
import { ALChip } from '@southleft/al-react';

figma.connect(ALChip, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3540-43526', {
  props: {
    type: figma.enum('Shape', {
      Squared: 'squared',
    }),
    variant: figma.enum('Variant', {
      Secondary: 'secondary',
    }),
  },
  example: (props) => (
    <ALChip
      type={props.type}
      variant={props.variant}
    >
      Chip
    </ALChip>
  ),
});
