/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-checkbox.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Checkbox"
 * component set (node 3539:42167).
 *
 * Mapped variant axes: Label, Checked, State, Checked.
 * Props the contract marks `omit` (no Figma axis): ariaDescribedBy, errorNote, fieldId, fieldNote, isRequired, name, value.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for error, field-note.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3539-42167', {
  props: {
    hideLabel: figma.enum('Label', {
      Hidden: true,
    }),
    isChecked: figma.enum('Checked', {
      On: true,
    }),
    isDisabled: figma.enum('State', {
      Disabled: true,
    }),
    isIndeterminate: figma.enum('Checked', {
      Indeterminate: true,
    }),
  },
  example: (props) => html`
    <al-checkbox
      hideLabel="${props.hideLabel}"
      isChecked="${props.isChecked}"
      isDisabled="${props.isDisabled}"
      isIndeterminate="${props.isIndeterminate}"
    >
      Checkbox
      <span slot="error">Error</span>
      <span slot="field-note">Field note</span>
    </al-checkbox>
  `,
});
