/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-card.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Card"
 * component set (node 3702:12161).
 *
 * Mapped variant axes: Variant.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for action-right, actions-end, actions-start, footer, header, image.
 */
import figma from '@figma/code-connect';
import { ALCard } from '@southleft/al-react';

figma.connect(ALCard, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3702-12161', {
  props: {
    variant: figma.enum('Variant', {
      Bare: 'bare',
    }),
  },
  example: (props) => (
    <ALCard
      variant={props.variant}
    >
      Card
      <span slot="action-right">Action right</span>
      <span slot="actions-end">Actions end</span>
      <span slot="actions-start">Actions start</span>
      <span slot="footer">Footer</span>
      <span slot="header">Header</span>
      <span slot="image">Image</span>
    </ALCard>
  ),
});
