/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-divider.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Divider"
 * component set (node 3543:46933).
 *
 * Mapped variant axes: Orientation.
 */
import figma from '@figma/code-connect';
import { ALDivider } from '@southleft/al-react';

figma.connect(ALDivider, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3543-46933', {
  props: {
    variant: figma.enum('Orientation', {
      Vertical: 'vertical',
    }),
  },
  example: (props) => (
    <ALDivider
      variant={props.variant}
    />
  ),
});
