/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-dialog.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Dialog"
 * component set (node 3704:13290).
 *
 * Mapped variant axes: none.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for footer, header, trigger.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3704-13290', {
  props: {},
  example: (props) => html`
    <al-dialog>
      Dialog
      <span slot="footer">Footer</span>
      <span slot="header">Header</span>
      <span slot="trigger">Trigger</span>
    </al-dialog>
  `,
});
