/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-drawer.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Drawer"
 * component set (node 3703:12781).
 *
 * Mapped variant axes: Alignment.
 * Props the contract marks `omit` (no Figma axis): ariaLabelledBy, disableBackdropClick, width.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for footer, header, trigger.
 */
import figma from '@figma/code-connect';
import { ALDrawer } from '@southleft/al-react';

figma.connect(ALDrawer, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3703-12781', {
  props: {
    alignment: figma.enum('Alignment', {
      Right: 'right',
    }),
  },
  example: (props) => (
    <ALDrawer
      alignment={props.alignment}
    >
      Drawer
      <span slot="footer">Footer</span>
      <span slot="header">Header</span>
      <span slot="trigger">Trigger</span>
    </ALDrawer>
  ),
});
