/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-drawer.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Drawer"
 * component set (node 3703:12781).
 *
 * Mapped variant axes: Alignment.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for footer, header, trigger.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3703-12781', {
  props: {
    alignment: figma.enum('Alignment', {
      Right: 'right',
    }),
  },
  example: (props) => html`
    <al-drawer
      alignment="${props.alignment}"
    >
      Drawer
      <span slot="footer">Footer</span>
      <span slot="header">Header</span>
      <span slot="trigger">Trigger</span>
    </al-drawer>
  `,
});
