/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-dialog.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Dialog"
 * component set (node 3704:13290).
 *
 * Mapped variant axes: none.
 * Props the contract marks `omit` (no Figma axis): ariaLabelledBy, dialogTrigger, disableClickOutside, heading, transitionDelay, width.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for footer, header, trigger.
 */
import figma from '@figma/code-connect';
import { ALDialog } from '@southleft/al-react';

figma.connect(ALDialog, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3704-13290', {
  props: {},
  example: (props) => (
    <ALDialog>
      Dialog
      <span slot="footer">Footer</span>
      <span slot="header">Header</span>
      <span slot="trigger">Trigger</span>
    </ALDialog>
  ),
});
