/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-empty-state.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Empty State"
 * component set (node 3570:4107).
 *
 * Mapped variant axes: none.
 * Props the contract marks `omit` (no Figma axis): description, heading.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for actions, icon.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3570-4107', {
  props: {},
  example: (props) => html`
    <al-empty-state>
      <span slot="actions">Actions</span>
      <span slot="icon">Icon</span>
    </al-empty-state>
  `,
});
