/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-field-note.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Field Note"
 * component set (node 3543:46961).
 *
 * Mapped variant axes: State, State.
 */
import figma from '@figma/code-connect';
import { ALFieldNote } from '@southleft/al-react';

figma.connect(ALFieldNote, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3543-46961', {
  props: {
    isDisabled: figma.enum('State', {
      Disabled: true,
    }),
    isError: figma.enum('State', {
      Error: true,
    }),
  },
  example: (props) => (
    <ALFieldNote
      isDisabled={props.isDisabled}
      isError={props.isError}
    >
      Field Note
    </ALFieldNote>
  ),
});
