/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-file-upload.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "File Upload"
 * component set (node 3544:51718).
 *
 * Mapped variant axes: Label, State, State.
 * Props the contract marks `omit` (no Figma axis): accept, ariaDescribedBy, errorNote, fieldId, fieldNote, fileSizeLimit, isRequired, label, multiple, name, textConfig, uploadFiles, uploadTime, value.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3544-51718', {
  props: {
    hideLabel: figma.enum('Label', {
      Hidden: true,
    }),
    isDisabled: figma.enum('State', {
      Disabled: true,
    }),
    isError: figma.enum('State', {
      Error: true,
    }),
  },
  example: (props) => html`
    <al-file-upload
      hideLabel="${props.hideLabel}"
      isDisabled="${props.isDisabled}"
      isError="${props.isError}"
    >
      File Upload
    </al-file-upload>
  `,
});
