/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-file-upload.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "File Upload"
 * component set (node 3544:51718).
 *
 * Mapped variant axes: Label, State, State.
 * Props the contract marks `omit` (no Figma axis): accept, ariaDescribedBy, errorNote, fieldId, fieldNote, fileSizeLimit, isRequired, label, multiple, name, textConfig, uploadFiles, uploadTime, value.
 */
import figma from '@figma/code-connect';
import { ALFileUpload } from '@southleft/al-react';

figma.connect(ALFileUpload, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3544-51718', {
  props: {
    hideLabel: figma.enum('Label', {
      Hidden: true,
    }),
    isDisabled: figma.enum('State', {
      Disabled: true,
    }),
    isError: figma.enum('State', {
      Error: true,
    }),
  },
  example: (props) => (
    <ALFileUpload
      hideLabel={props.hideLabel}
      isDisabled={props.isDisabled}
      isError={props.isError}
    >
      File Upload
    </ALFileUpload>
  ),
});
