/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-heading.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Heading"
 * component set (node 3543:47001).
 *
 * Mapped variant axes: Variant.
 * Props the contract binds to an axis this generator could not map: isBold
 * (reasons in skipped.json — they are drift, not omissions).
 * Props the contract marks `omit` (no Figma axis): tagName.
 */
import figma from '@figma/code-connect';
import { ALHeading } from '@southleft/al-react';

figma.connect(ALHeading, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3543-47001', {
  props: {
    variant: figma.enum('Variant', {
      'Display Lg': 'display-lg',
      'Display Md': 'display-md',
      'Display Sm': 'display-sm',
      Lg: 'lg',
      Md: 'md',
      Sm: 'sm',
    }),
  },
  example: (props) => (
    <ALHeading
      variant={props.variant}
    >
      Heading
    </ALHeading>
  ),
});
