/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-input-stepper.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Input Stepper"
 * component set (node 3558:61366).
 *
 * Mapped variant axes: Label, State, Variant.
 * Props the contract binds to an axis this generator could not map: label
 * (reasons in skipped.json — they are drift, not omissions).
 * Props the contract marks `omit` (no Figma axis): ariaDescribedBy, count, errorNote, fieldId, fieldNote, isReadonly, isRequired, max, min, name, placeholder, step, value.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for error, field-note.
 */
import figma from '@figma/code-connect';
import { ALInputStepper } from '@southleft/al-react';

figma.connect(ALInputStepper, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3558-61366', {
  props: {
    hideLabel: figma.enum('Label', {
      Hidden: true,
    }),
    isDisabled: figma.enum('State', {
      Disabled: true,
    }),
    variant: figma.enum('Variant', {
      Segmented: 'segmented',
      Trailing: 'trailing',
    }),
  },
  example: (props) => (
    <ALInputStepper
      hideLabel={props.hideLabel}
      isDisabled={props.isDisabled}
      variant={props.variant}
    >
      <span slot="error">Error</span>
      <span slot="field-note">Field note</span>
    </ALInputStepper>
  ),
});
