/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-input.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Input"
 * component set (node 3544:48650).
 *
 * Mapped variant axes: Label, State, State, State, Label Position.
 * Props the contract marks `omit` (no Figma axis): ariaDescribedBy, autoComplete, errorNote, fieldId, fieldNote, isActive, isReadonly, label, max, maxLength, maxLengthValue, min, minLength, name, placeholder, type, value.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for before, after, error, field-note.
 */
import figma from '@figma/code-connect';
import { ALInput } from '@southleft/al-react';

figma.connect(ALInput, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3544-48650', {
  props: {
    hideLabel: figma.enum('Label', {
      Hidden: true,
    }),
    isDisabled: figma.enum('State', {
      Disabled: true,
    }),
    isError: figma.enum('State', {
      Error: true,
    }),
    isFocused: figma.enum('State', {
      Focus: true,
    }),
    labelPosition: figma.enum('Label Position', {
      Inset: 'inset',
      Top: 'top',
    }),
  },
  example: (props) => (
    <ALInput
      hideLabel={props.hideLabel}
      isDisabled={props.isDisabled}
      isError={props.isError}
      isFocused={props.isFocused}
      labelPosition={props.labelPosition}
    >
      <span slot="before">Before</span>
      <span slot="after">After</span>
      <span slot="error">Error</span>
      <span slot="field-note">Field note</span>
    </ALInput>
  ),
});
