/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-link.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Link"
 * component set (node 3543:47075).
 *
 * Mapped variant axes: none.
 * Props the contract marks `omit` (no Figma axis): ariaLabelledBy, href, label, linkTitle, target.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for after.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3543-47075', {
  props: {},
  example: (props) => html`
    <al-link>
      Link
      <span slot="after">After</span>
    </al-link>
  `,
});
