/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-list-item.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "List Item"
 * component set (node 3543:47175).
 *
 * Mapped variant axes: State, Current, State, State, Variant.
 * Props the contract marks `omit` (no Figma axis): behavior, flyoutPosition, href, onClick, target, value.
 */
import figma from '@figma/code-connect';
import { ALListItem } from '@southleft/al-react';

figma.connect(ALListItem, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3543-47175', {
  props: {
    isActive: figma.enum('State', {
      Active: true,
    }),
    isCurrent: figma.enum('Current', {
      Yes: true,
    }),
    isDisabled: figma.enum('State', {
      Disabled: true,
    }),
    isError: figma.enum('State', {
      Error: true,
    }),
    variant: figma.enum('Variant', {
      Static: 'static',
    }),
  },
  example: (props) => (
    <ALListItem
      isActive={props.isActive}
      isCurrent={props.isCurrent}
      isDisabled={props.isDisabled}
      isError={props.isError}
      variant={props.variant}
    >
      List Item
    </ALListItem>
  ),
});
