/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-menu.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Menu"
 * component set (node 3558:61424).
 *
 * Mapped variant axes: Variant.
 * Props the contract marks `omit` (no Figma axis): height, id, indentGroupItems, label, width.
 */
import figma from '@figma/code-connect';
import { ALMenu } from '@southleft/al-react';

figma.connect(ALMenu, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3558-61424', {
  props: {
    variant: figma.enum('Variant', {
      Simple: 'simple',
    }),
  },
  example: (props) => (
    <ALMenu
      variant={props.variant}
    >
      Menu
    </ALMenu>
  ),
});
