/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-menu-item.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Menu Item"
 * component set (node 3543:47347).
 *
 * Mapped variant axes: State, Role, Selected.
 * Props the contract binds to an axis this generator could not map: isExpandableHeader, isFocused
 * (reasons in skipped.json — they are drift, not omissions).
 * Props the contract marks `omit` (no Figma axis): ariaControls, groupId, href, idx, indentation, isExpanded, isHidden, linkTitle, target, value.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for before.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3543-47347', {
  props: {
    isDisabled: figma.enum('State', {
      Disabled: true,
    }),
    isHeader: figma.enum('Role', {
      Header: true,
    }),
    isSelected: figma.enum('Selected', {
      Yes: true,
    }),
  },
  example: (props) => html`
    <al-menu-item
      isDisabled="${props.isDisabled}"
      isHeader="${props.isHeader}"
      isSelected="${props.isSelected}"
    >
      <span slot="before">Before</span>
      Menu Item
    </al-menu-item>
  `,
});
