/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-menu.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Menu"
 * component set (node 3558:61424).
 *
 * Mapped variant axes: Variant.
 * Props the contract marks `omit` (no Figma axis): height, id, indentGroupItems, label, width.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3558-61424', {
  props: {
    variant: figma.enum('Variant', {
      Simple: 'simple',
    }),
  },
  example: (props) => html`
    <al-menu
      variant="${props.variant}"
    >
      Menu
    </al-menu>
  `,
});
