/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-progress.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Progress"
 * component set (node 3557:58565).
 *
 * Mapped variant axes: Size, Shape, Label.
 * Props the contract marks `omit` (no Figma axis): currentProgress, duration, endProgress, labelAria, labelType.
 */
import figma from '@figma/code-connect';
import { ALProgress } from '@southleft/al-react';

figma.connect(ALProgress, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3557-58565', {
  props: {
    circleSize: figma.enum('Size', {
      Lg: 'lg',
      Md: 'md',
      Xl: 'xl',
    }),
    isCircle: figma.enum('Shape', {
      Circle: true,
    }),
    showLabel: figma.enum('Label', {
      Shown: true,
    }),
  },
  example: (props) => (
    <ALProgress
      circleSize={props.circleSize}
      isCircle={props.isCircle}
      showLabel={props.showLabel}
    />
  ),
});
