/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-pagination.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Pagination"
 * component set (node 3558:61528).
 *
 * Mapped variant axes: Variant.
 * Props the contract marks `omit` (no Figma axis): ariaLabel, currentItem, nextButtonText, pageSize, pageSizeLabel, pageSizeOptions, prevButtonText, totalRecords.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for label, next, prev.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3558-61528', {
  props: {
    variant: figma.enum('Variant', {
      Small: 'small',
    }),
  },
  example: (props) => html`
    <al-pagination
      variant="${props.variant}"
    >
      <span slot="label">Label</span>
      <span slot="next">Next</span>
      <span slot="prev">Prev</span>
    </al-pagination>
  `,
});
