/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-pagination.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Pagination"
 * component set (node 3558:61528).
 *
 * Mapped variant axes: Variant.
 * Props the contract marks `omit` (no Figma axis): ariaLabel, currentItem, nextButtonText, pageSize, pageSizeLabel, pageSizeOptions, prevButtonText, totalRecords.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for label, next, prev.
 */
import figma from '@figma/code-connect';
import { ALPagination } from '@southleft/al-react';

figma.connect(ALPagination, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3558-61528', {
  props: {
    variant: figma.enum('Variant', {
      Small: 'small',
    }),
  },
  example: (props) => (
    <ALPagination
      variant={props.variant}
    >
      <span slot="label">Label</span>
      <span slot="next">Next</span>
      <span slot="prev">Prev</span>
    </ALPagination>
  ),
});
