/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-popover.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Popover"
 * component set (node 3702:12374).
 *
 * Mapped variant axes: Position.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for footer, header, trigger.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3702-12374', {
  props: {
    position: figma.enum('Position', {
      'Bottom-center': 'bottom-center',
      Left: 'left',
      Right: 'right',
    }),
  },
  example: (props) => html`
    <al-popover
      position="${props.position}"
    >
      Popover
      <span slot="footer">Footer</span>
      <span slot="header">Header</span>
      <span slot="trigger">Trigger</span>
    </al-popover>
  `,
});
