/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-pagination-item.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Pagination Item"
 * component set (node 3543:47406).
 *
 * Mapped variant axes: State, Kind, Selected.
 * Props the contract marks `omit` (no Figma axis): ariaLabel, href.
 */
import figma from '@figma/code-connect';
import { ALPaginationItem } from '@southleft/al-react';

figma.connect(ALPaginationItem, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3543-47406', {
  props: {
    isDisabled: figma.enum('State', {
      Disabled: true,
    }),
    isExpandable: figma.enum('Kind', {
      Expandable: true,
    }),
    isSelected: figma.enum('Selected', {
      Yes: true,
    }),
  },
  example: (props) => (
    <ALPaginationItem
      isDisabled={props.isDisabled}
      isExpandable={props.isExpandable}
      isSelected={props.isSelected}
    >
      Pagination Item
    </ALPaginationItem>
  ),
});
