/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-radio-group.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Radio Group"
 * component set (node 3570:3422).
 *
 * Mapped variant axes: Legend, State, State.
 * Props the contract marks `omit` (no Figma axis): ariaDescribedBy, errorNote, fieldId, fieldNote, isRequired.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for error, field-note.
 */
import figma from '@figma/code-connect';
import { ALRadioGroup } from '@southleft/al-react';

figma.connect(ALRadioGroup, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3570-3422', {
  props: {
    hideLegend: figma.enum('Legend', {
      Hidden: true,
    }),
    isDisabled: figma.enum('State', {
      Disabled: true,
    }),
    isError: figma.enum('State', {
      Error: true,
    }),
  },
  example: (props) => (
    <ALRadioGroup
      hideLegend={props.hideLegend}
      isDisabled={props.isDisabled}
      isError={props.isError}
    >
      Radio Group
      <span slot="error">Error</span>
      <span slot="field-note">Field note</span>
    </ALRadioGroup>
  ),
});
