/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-range.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Range"
 * component set (node 3558:61875).
 *
 * Mapped variant axes: Behavior, Output, State.
 * Props the contract marks `omit` (no Figma axis): ariaDescribedBy, errorNote, fieldId, fieldNote, handleLabelUnit, label, lowerRangeValue, max, maxSelected, min, minSelected, name, step, upperRangeValue, value.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for before, after, error, field-note, label.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3558-61875', {
  props: {
    behavior: figma.enum('Behavior', {
      Range: 'range',
    }),
    hasOutput: figma.enum('Output', {
      Yes: true,
    }),
    isDisabled: figma.enum('State', {
      Disabled: true,
    }),
  },
  example: (props) => html`
    <al-range
      behavior="${props.behavior}"
      hasOutput="${props.hasOutput}"
      isDisabled="${props.isDisabled}"
    >
      <span slot="before">Before</span>
      <span slot="after">After</span>
      <span slot="error">Error</span>
      <span slot="field-note">Field note</span>
      <span slot="label">Label</span>
    </al-range>
  `,
});
