/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-radio.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Radio"
 * component set (node 3543:47540).
 *
 * Mapped variant axes: Label, Checked, State, State.
 * Props the contract marks `omit` (no Figma axis): ariaDescribedBy, errorNote, fieldId, fieldNote, isRequired, name, value.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for error, field-note.
 */
import figma from '@figma/code-connect';
import { ALRadio } from '@southleft/al-react';

figma.connect(ALRadio, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3543-47540', {
  props: {
    hideLabel: figma.enum('Label', {
      Hidden: true,
    }),
    isChecked: figma.enum('Checked', {
      On: true,
    }),
    isDisabled: figma.enum('State', {
      Disabled: true,
    }),
    isError: figma.enum('State', {
      Error: true,
    }),
  },
  example: (props) => (
    <ALRadio
      hideLabel={props.hideLabel}
      isChecked={props.isChecked}
      isDisabled={props.isDisabled}
      isError={props.isError}
    >
      Radio
      <span slot="error">Error</span>
      <span slot="field-note">Field note</span>
    </ALRadio>
  ),
});
