/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-select.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Select"
 * component set (node 3704:13389).
 *
 * Mapped variant axes: Label.
 * Props the contract binds to an axis this generator could not map: label
 * (reasons in skipped.json — they are drift, not omissions).
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for before, error, field-note.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3704-13389', {
  props: {
    hideLabel: figma.enum('Label', {
      Hidden: true,
    }),
  },
  example: (props) => html`
    <al-select
      hideLabel="${props.hideLabel}"
    >
      <span slot="before">Before</span>
      Select
      <span slot="error">Error</span>
      <span slot="field-note">Field note</span>
    </al-select>
  `,
});
