/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-text-block.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Text Block"
 * component set (node 3694:10744).
 *
 * Mapped variant axes: none.
 * Props the contract marks `omit` (no Figma axis): maxWidth.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3694-10744', {
  props: {},
  example: (props) => html`
    <al-text-block>
      Text Block
    </al-text-block>
  `,
});
