/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-tab-panel.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Tab Panel"
 * component set (node 3543:47875).
 *
 * Mapped variant axes: none.
 * Props the contract marks `omit` (no Figma axis): ariaId, ariaLabelledBy, idx, isActive.
 */
import figma from '@figma/code-connect';
import { ALTabPanel } from '@southleft/al-react';

figma.connect(ALTabPanel, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3543-47875', {
  props: {},
  example: (props) => (
    <ALTabPanel>
      Tab Panel
    </ALTabPanel>
  ),
});
