/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-tabs.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Tabs"
 * component set (node 3558:61955).
 *
 * Mapped variant axes: Variant.
 * Props the contract marks `omit` (no Figma axis): activeIndex.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for panel.
 */
import figma from '@figma/code-connect';
import { ALTabs } from '@southleft/al-react';

figma.connect(ALTabs, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3558-61955', {
  props: {
    variant: figma.enum('Variant', {
      Stretch: 'stretch',
    }),
  },
  example: (props) => (
    <ALTabs
      variant={props.variant}
    >
      Tabs
      <span slot="panel">Panel</span>
    </ALTabs>
  ),
});
