/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-table.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Table"
 * component set (node 3558:62965).
 *
 * Mapped variant axes: Selectable.
 * Props the contract marks `omit` (no Figma axis): caption, columns, data, hideCaption, rowKey, sortDirection, sortKey.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3558-62965', {
  props: {
    isSelectable: figma.enum('Selectable', {
      Yes: true,
    }),
  },
  example: (props) => html`
    <al-table
      isSelectable="${props.isSelectable}"
    >
      Table
    </al-table>
  `,
});
