/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-toggle-button.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Toggle Button"
 * component set (node 3543:47985).
 *
 * Mapped variant axes: Selected, Size, Variant.
 * Props the contract marks `omit` (no Figma axis): hasToggle.
 */
import figma from '@figma/code-connect';
import { ALToggleButton } from '@southleft/al-react';

figma.connect(ALToggleButton, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3543-47985', {
  props: {
    isSelected: figma.enum('Selected', {
      Yes: true,
    }),
    isSmall: figma.enum('Size', {
      Small: true,
    }),
    variant: figma.enum('Variant', {
      Background: 'background',
    }),
  },
  example: (props) => (
    <ALToggleButton
      isSelected={props.isSelected}
      isSmall={props.isSmall}
      variant={props.variant}
    >
      Toggle Button
    </ALToggleButton>
  ),
});
