/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-table.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Table"
 * component set (node 3558:62965).
 *
 * Mapped variant axes: none.
 * Props the contract binds to an axis this generator could not map: sortDirection
 * (reasons in skipped.json — they are drift, not omissions).
 * Props the contract marks `omit` (no Figma axis): caption, columns, data, hideCaption, rowKey, sortKey.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3558-62965', {
  props: {},
  example: (props) => html`
    <al-table>
      Table
    </al-table>
  `,
});
