/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-text-block.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Text Passage"
 * component set (node 3435:888).
 *
 * Mapped variant axes: none.
 * Props the contract marks `omit` (no Figma axis): maxWidth.
 */
import figma from '@figma/code-connect';
import { ALTextBlock } from '@southleft/al-react';

figma.connect(ALTextBlock, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3435-888', {
  props: {},
  example: (props) => (
    <ALTextBlock>
      Text Passage
    </ALTextBlock>
  ),
});
