/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-tab.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Tab"
 * component set (node 3543:47793).
 *
 * Mapped variant axes: Active, State.
 * Props the contract marks `omit` (no Figma axis): ariaControls, ariaId, idx.
 */
import figma from '@figma/code-connect';
import { ALTab } from '@southleft/al-react';

figma.connect(ALTab, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3543-47793', {
  props: {
    isActive: figma.enum('Active', {
      Yes: true,
    }),
    isDisabled: figma.enum('State', {
      Disabled: true,
    }),
  },
  example: (props) => (
    <ALTab
      isActive={props.isActive}
      isDisabled={props.isDisabled}
    >
      Tab
    </ALTab>
  ),
});
