/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-table.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Table"
 * component set (node 3558:62965).
 *
 * Mapped variant axes: none.
 * Props the contract binds to an axis this generator could not map: sortDirection
 * (reasons in skipped.json — they are drift, not omissions).
 * Props the contract marks `omit` (no Figma axis): caption, columns, data, hideCaption, rowKey, sortKey.
 */
import figma from '@figma/code-connect';
import { ALTable } from '@southleft/al-react';

figma.connect(ALTable, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3558-62965', {
  props: {},
  example: (props) => (
    <ALTable>
      Table
    </ALTable>
  ),
});
