/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-tooltip.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Tooltip"
 * component set (node 3703:12726).
 *
 * Mapped variant axes: Arrow, Position.
 * Named slots below are PLACEHOLDERS: slot content is consumer-supplied, so
 * the contract records no default for prefix, trigger.
 */
import figma from '@figma/code-connect';
import { ALTooltip } from '@southleft/al-react';

figma.connect(ALTooltip, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3703-12726', {
  props: {
    hasArrow: figma.enum('Arrow', {
      Yes: true,
    }),
    position: figma.enum('Position', {
      Bottom: 'bottom',
      Left: 'left',
      Right: 'right',
      Top: 'top',
    }),
  },
  example: (props) => (
    <ALTooltip
      hasArrow={props.hasArrow}
      position={props.position}
    >
      Tooltip
      <span slot="prefix">Prefix</span>
      <span slot="trigger">Trigger</span>
    </ALTooltip>
  ),
});
