/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-toggle-button.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — web component surface for the "Toggle Button"
 * component set (node 3543:47985).
 *
 * Mapped variant axes: Selected, Size, Variant.
 * Props the contract marks `omit` (no Figma axis): hasToggle.
 */
import figma, { html } from '@figma/code-connect/html';

figma.connect('https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3543-47985', {
  props: {
    isSelected: figma.enum('Selected', {
      Yes: true,
    }),
    isSmall: figma.enum('Size', {
      Small: true,
    }),
    variant: figma.enum('Variant', {
      Background: 'background',
    }),
  },
  example: (props) => html`
    <al-toggle-button
      isSelected="${props.isSelected}"
      isSmall="${props.isSmall}"
      variant="${props.variant}"
    >
      Toggle Button
    </al-toggle-button>
  `,
});
