/**
 * GENERATED by scripts/contracts/build-code-connect.mjs from
 * .altitude/contracts/altitude/al-toggle.contract.json — DO NOT HAND-EDIT.
 * Re-run the generator; `--check` is the drift gate.
 *
 * Figma Code Connect — React wrapper surface for the "Toggle"
 * component set (node 3543:48094).
 *
 * Mapped variant axes: Checked, State.
 * Props the contract marks `omit` (no Figma axis): fieldId, label, name.
 */
import figma from '@figma/code-connect';
import { ALToggle } from '@southleft/al-react';

figma.connect(ALToggle, 'https://www.figma.com/design/y83n4o9LOGs74oAoguFcGS/?node-id=3543-48094', {
  props: {
    isChecked: figma.enum('Checked', {
      On: true,
    }),
    isDisabled: figma.enum('State', {
      Disabled: true,
    }),
  },
  example: (props) => (
    <ALToggle
      isChecked={props.isChecked}
      isDisabled={props.isDisabled}
    />
  ),
});
