// T1.1 — Style Dictionary v5 parallel pipeline.
//
// Runs alongside the v3 pipeline (`tokens-config.js`). Reads DTCG source
// from `styles/tokens-dtcg/` and emits CSS/SCSS/JSON to
// `styles/dist-v5/` so the diff against v3's `styles/dist/` is the
// byte-comparability check the plan demands.
//
// Acceptance (per T1.1):
//   pnpm build:tokens emits CSS whose `--al-*` variable set is
//   byte-identical to v3 output.

import { promises as fs } from 'node:fs';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';
import { usesReferences, getReferences } from 'style-dictionary/utils';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SD_ROOT = __dirname; // .../libs/al-web-components/styles
const WORKSPACE_ROOT = path.resolve(SD_ROOT, '..'); // .../libs/al-web-components

const themePrefix = 'al';
const themeFontWeightRegular = '400';
const themeFontWeightMedium = '500';
const themeFontWeightBold = '600';

/*
 * Named weight -> CSS numeric. This used to be a BINARY: `'Bold' ? 600 : 400`,
 * so the pipeline could express exactly two weights and every other name
 * silently collapsed to 400 — a token authored as "Medium" emitted 400 and gave
 * no warning that it had been flattened. The v2 canvas uses three (400 body,
 * 500 chips and the mono metadata face, 600 controls and headings), so the map
 * is explicit and an unknown name still falls back to regular rather than
 * throwing.
 */
const FONT_WEIGHTS = {
  Regular: themeFontWeightRegular,
  Medium: themeFontWeightMedium,
  Bold: themeFontWeightBold,
};
const themeFontBaseSize = 16;
const themeSpaceBaseSize = 16;
const themeFontFamilyFallback = 'sans-serif';
const comment = '\n\n/* This file is auto-generated by Style Dictionary. Do not edit directly. */\n';

// ---------- helpers (ported from v3 verbatim) ----------

function formatBoxShadowValue(value) {
  if (Array.isArray(value)) {
    return value
      .map((s) => `${s.x}px ${s.y}px ${s.blur}px ${s.spread}px ${s.color}`)
      .join(', ');
  }
  return `${value.x}px ${value.y}px ${value.blur}px ${value.spread}px ${value.color}`;
}

function formatFontWeightValue(value) {
  return FONT_WEIGHTS[value] ?? themeFontWeightRegular;
}

function formatTypographyValue(value) {
  const fontSize = `${parseFloat(value.fontSize) / themeFontBaseSize}rem`;
  const lineHeight = `${parseFloat(value.lineHeight) / themeFontBaseSize}rem`;
  return `${formatFontWeightValue(value.fontWeight)} ${fontSize}/${lineHeight} ${value.fontFamily}, ${themeFontFamilyFallback}`;
}

/**
 * The composite typography token authors FIVE sub-values; the CSS `font`
 * shorthand can only carry three of them. `letterSpacing` and `textDecoration`
 * are not `font` sub-properties at all, so they were silently dropped on the
 * floor - every `letterSpacing` the designers authored was inert.
 * `formatLetterSpacingValue` is half of putting them back.
 *
 * Two things to know:
 *
 * 1. UNIT. Figma (and therefore
 *    `tier-1/typography.json`) authors letter-spacing as a PERCENTAGE of the
 *    font size. CSS `letter-spacing` takes a `<length>` and rejects `%`
 *    outright - emitting `letter-spacing: 1%` would produce a declaration the
 *    parser discards, i.e. the same inert result by a longer route. 1% of the
 *    font size is exactly `0.01em`, so `% -> em` is lossless.
 *
 * 2. ZERO IS STILL EMITTED, as the CSS keyword `normal`. The first cut skipped
 *    the 20 presets whose authored tracking is zero, on the grounds that
 *    `0em` is just the CSS initial value and emitting it is noise. That was
 *    wrong, and `scripts/check-token-usage.mjs` said so: the mixins then read
 *    `var(--al-theme-typography-body-md-letter-spacing, normal)` against a
 *    name the pipeline never emitted, which is the tool's PHANTOM case - the
 *    hardcoded `normal` in the mixin always won and no brand could add
 *    tracking to body copy. Emitting every preset's tracking costs 20 `:root`
 *    declarations and buys a fully brand-restatable axis, and the mixins carry
 *    no hardcoded fallback at all. `normal` rather than `0` on purpose: `0`
 *    forbids the UA's justification adjustment, `normal` permits it, and
 *    "no tracking authored" means the latter.
 */
function formatLetterSpacingValue(raw) {
  if (raw === undefined || raw === null) return null;
  const str = String(raw).trim();
  const pct = /^(-?[\d.]+)%$/.exec(str);
  const value = pct ? `${parseFloat(pct[1]) / 100}em` : str;
  if (!Number.isNaN(parseFloat(value)) && parseFloat(value) === 0) return 'normal';
  return value;
}

/**
 * The other half — and the reason it always returns `null` today.
 *
 * `textDecoration` is only ever non-`none` on the `-underline` presets, and
 * every emitter below filters `-underline` (and `-italic`) out of the output
 * set entirely. So on the tokens that ARE emitted the authored value is
 * uniformly `{text-decoration.none}`, and emitting it would add 40 `:root`
 * declarations of the CSS initial value with no call site able to observe a
 * difference.
 *
 * The honest fix for text-decoration is therefore NOT here: it is to stop
 * filtering the `-underline` presets out of emission, which is a change to the
 * public token surface (10 new tier-1 + 10 new tier-2 names) and a design
 * decision, not a formatter bug. Recorded here rather than left implicit so
 * the next reader does not re-derive it.
 */
function formatTextDecorationValue(raw) {
  if (raw === undefined || raw === null) return null;
  const str = String(raw).trim();
  return str === 'none' ? null : str;
}

/**
 * The `[name, value]` pairs a single token contributes: itself, plus any
 * companion custom properties carrying composite sub-values that the primary
 * value's CSS shorthand cannot express.
 *
 * Emitted for every typography preset in BOTH tiers, and for the same reason
 * the primary is: the tier-2
 * mixins in `styles/core/mixins/typography.scss` read the tier-2 custom
 * property, so a tier-2 preset without its companion would silently lose the
 * tracking the tier-1 preset it aliases carries.
 *
 * `referenceName` mirrors the `outputReferences` treatment of the primary
 * value. When it is supplied (a tier-2 token whose value is a whole-string
 * alias) the companion is emitted as `var(--al-<tier-1>-letter-spacing)`
 * rather than a copy of the resolved literal, so the alias chain stays intact
 * and a brand restating the tier-1 preset moves the tier-2 tracking with it.
 */
function companionsFor(token, primaryName, referenceName) {
  const isPreset = token.name.startsWith('typography-preset-');
  const isThemePreset = token.name.startsWith('theme-typography-');
  if (!isPreset && !isThemePreset) return [];
  const value = tokenValue(token);
  if (!value || typeof value !== 'object') return [];
  const pairs = [];
  const asRef = (suffix) => `var(--${themePrefix}-${referenceName}${suffix})`;
  const tracking = formatLetterSpacingValue(value.letterSpacing);
  if (tracking !== null) {
    pairs.push([primaryName + '-letter-spacing', referenceName ? asRef('-letter-spacing') : tracking]);
  }
  const decoration = formatTextDecorationValue(value.textDecoration);
  if (decoration !== null) {
    pairs.push([primaryName + '-text-decoration', referenceName ? asRef('-text-decoration') : decoration]);
  }
  return pairs;
}

function formatSpaceValue(value) {
  return `${parseFloat(value) / themeSpaceBaseSize}rem`;
}

// SD v5 stores DTCG values under `$value` when `usesDtcg: true`. Wrap the
// token access so the rest of the format code can stay structurally close
// to the v3 implementation.
function tokenValue(token) {
  return '$value' in token ? token.$value : token.value;
}
function tokenOriginalValue(token) {
  return '$value' in token.original ? token.original.$value : token.original.value;
}

// ---------- custom transform groups (mirror v3 — no DTCG shorthand transforms) ----------
//
// SD v5's `css`/`scss` groups inject `typography/css/shorthand`,
// `shadow/css/shorthand`, etc. that coerce composite tokens into CSS strings
// BEFORE our format runs. v3 had no such transforms — our custom formatters
// (`formatTypographyValue`, `formatBoxShadowValue`) need the raw value
// objects. Register replacement groups that strip the shorthand transforms.

//
// The list below is only the transforms that actually FIRE against this token
// tree, and that is load-bearing rather than tidiness. `time/seconds`,
// `html/icon`, `size/rem`, `asset/url` and `cubicBezier/css` all select on
// `$type`, and every one of them was inert here because the tree carried
// Legacy `$type` values (`sizing`, `fontSizes`, `boxShadow`, `other`, …)
// that no SD filter recognises. Making those `$type` values DTCG-conformant
// would have silently switched all five on:
//
//   - `size/rem` would begin rewriting every `dimension`. It happens to
//     preserve an explicit unit, so `14px` survives — but that is a detail of
//     SD 5.4's implementation, not a contract, and `formatSpaceValue` already
//     does this conversion by hand for the space scale, so the two would race.
//   - `time/seconds` would rewrite the `duration` scale, whose values are
//     already authored in seconds (`0.1s`).
//   - `cubicBezier/css` expects a 4-number ARRAY; this tree authors easing as
//     CSS strings (`ease`, `cubic-bezier(0.2,0,0,1)`), which it cannot consume.
//
// Dropping them is a no-op TODAY (they match nothing today, by construction)
// and is what made the `$type` conformance pass value-neutral. Verified by
// diffing the full `dist-v5/` emission before and after: byte-identical.
// NOTE: these are inert only while the affected `$type` values stay
// non-conformant — relabelling e.g. animation.timing to DTCG `cubicBezier`
// switches `cubicBezier/css` back on. See the DTCG-conformance idea in .mm/ideas/.
const V3_SHAPE_TRANSFORMS = ['attribute/cti', 'name/kebab', 'color/css'];

StyleDictionary.registerTransformGroup({ name: 'css-v3-shape', transforms: V3_SHAPE_TRANSFORMS });
StyleDictionary.registerTransformGroup({ name: 'scss-v3-shape', transforms: V3_SHAPE_TRANSFORMS });

// ---------- custom formats (ported from v3 to v5 API) ----------

/**
 * The one place a declaration list becomes a CSS rule.
 *
 * `selector` and `layer` are FILE OPTIONS, not literals (R1 of
 * `2026-07-28-scoped-token-emission-brand-wiring`). The defaults —
 * `':root'` and no layer — reproduce the pre-existing output byte for byte,
 * which is the entire back-compat strategy: ten apps, two Storybook previews
 * and ten SCSS files consume the flat `:root` artifacts and none of them had
 * to change.
 */
function renderRule(pairs, { selector = ':root', layer = null } = {}) {
  const indent = layer ? '    ' : '  ';
  const decls = pairs.map(([name, value]) => `${indent}${name}: ${value};`).join('\n');
  if (!layer) return `${selector} {\n${decls}\n}\n`;
  return `@layer ${layer} {\n  ${selector} {\n${decls}\n  }\n}\n`;
}

StyleDictionary.registerFormat({
  name: 'tokens',
  format: ({ dictionary, options }) => {
    const pairs = dictionary.allTokens
      .filter(
        (token) =>
          !token.name.endsWith('-italic') &&
          !token.name.endsWith('-underline') &&
          !token.name.includes('breakpoint')
      )
      .flatMap((token) => {
        let name;
        let value = tokenValue(token);

        if (token.name.includes('font-weight')) {
          name = token.name;
          value = formatFontWeightValue(tokenValue(token));
        } else if (token.name.includes('typography')) {
          name = token.name.endsWith('-regular') ? token.name.replace('-regular', '') : token.name;
          value = formatTypographyValue(tokenValue(token));
        } else if (token.name.includes('box-shadow')) {
          name = token.name;
          value = formatBoxShadowValue(tokenValue(token));
        } else if (!token.name.includes('base') && token.name.includes('space')) {
          name = token.name;
          value = formatSpaceValue(tokenValue(token));
        } else {
          name = token.name;
          value = tokenValue(token);
        }

        // Captured so the composite companions below can be emitted as
        // references too, instead of copies of the resolved literal.
        let referenceName = null;
        if (token.name.includes('theme') && options.outputReferences) {
          const origValue = tokenOriginalValue(token);
          if (usesReferences(origValue)) {
            const refs = getReferences(origValue, dictionary.tokens, { usesDtcg: true });
            refs.forEach((ref) => {
              const refName = ref.name.endsWith('-regular') ? ref.name.replace('-regular', '') : ref.name;
              referenceName = refName;
              value = `var(--${themePrefix}-${refName})`;
            });
          }
        }
        const primary = `--${themePrefix}-${name}`;
        return [[primary, value], ...companionsFor(token, primary, referenceName)];
      });

    // R2 — scoped (host) emission is a DELTA, not a copy.
    //
    // `options.onlyNames` (a Set of `--al-…` names) and `options.omitEqualTo`
    // (a Map of `--al-…` -> value read back from an already-emitted `:root`
    // artifact) narrow the declaration list to exactly what the host has to
    // restate. Both are absent for every `:root` file, so those keep emitting
    // the full surface unchanged.
    //
    // Deltas rather than full 17 KB copies because a host INHERITS the base
    // `:root` values through the shadow boundary — restating them costs
    // ~105 KB across the matrix (3.2x the CI bundle allowance) to compute the
    // same thing. See the spec's T9 measurement.
    const only = options.onlyNames ?? null;
    const base = options.omitEqualTo ?? null;
    const kept = pairs.filter(
      ([name, value]) =>
        (!only || only.has(name)) && (!base || base.get(name) !== String(value))
    );

    return comment + renderRule(kept, { selector: options.selector, layer: options.layer });
  },
});

StyleDictionary.registerFormat({
  name: 'al-scss-vars',
  format: ({ dictionary, options }) => {
    const breakpointVariables = dictionary.allTokens
      .filter((token) => token.name.includes('breakpoint'))
      .map((token) => {
        let value = JSON.parse(JSON.stringify(tokenValue(token)));
        const origValue = tokenOriginalValue(token);
        if (options.outputReferences && usesReferences(origValue)) {
          const refs = getReferences(origValue, dictionary.tokens, { usesDtcg: true });
          value = refs.map((ref) => `breakpoint-${ref.name}`).join(', ');
        }
        return `$${themePrefix}-${token.name}: ${value};`;
      })
      .join('\n');

    const themeDeclaration = `$${themePrefix}-theme-prefix: '${themePrefix}';\n`;
    return comment + themeDeclaration + breakpointVariables;
  },
});

StyleDictionary.registerFormat({
  name: 'al-json-flat',
  format: ({ dictionary, options }) => {
    const entries = dictionary.allTokens
      .filter((token) => !token.name.endsWith('-italic') && !token.name.endsWith('-underline'))
      .flatMap((token) => {
        let name;
        let value;
        if (token.name.includes('font-weight')) {
          name = token.name;
          value = formatFontWeightValue(tokenValue(token));
        } else if (token.name.includes('typography')) {
          name = token.name.endsWith('-regular') ? token.name.replace('-regular', '') : token.name;
          value = formatTypographyValue(tokenValue(token));
        } else if (token.name.includes('box-shadow')) {
          name = token.name;
          value = formatBoxShadowValue(tokenValue(token));
        } else {
          name = token.name;
          value = tokenValue(token);
        }

        // Captured so the composite companions below can be emitted as
        // references too, instead of copies of the resolved literal.
        let referenceName = null;
        if (token.name.includes('theme') && options.outputReferences) {
          const origValue = tokenOriginalValue(token);
          if (usesReferences(origValue)) {
            const refs = getReferences(origValue, dictionary.tokens, { usesDtcg: true });
            refs.forEach((ref) => {
              const refName = ref.name.endsWith('-regular') ? ref.name.replace('-regular', '') : ref.name;
              referenceName = refName;
              value = `var(--${themePrefix}-${refName})`;
            });
          }
        }
        // companionsFor returns `--al-…` CSS custom-property names; this
        // format keys on the bare `al-…` name, so strip the leading `--`.
        return [
          [`${themePrefix}-${name}`, value],
          ...companionsFor(token, `--${themePrefix}-${name}`, referenceName).map(([n, v]) => [n.slice(2), v]),
        ];
      });

    const variables = entries
      .map(([name, value], index) => `  "${name}": "${value}"${index === entries.length - 1 ? '' : ','}`)
      .join('\n');

    return `{\n${variables}\n}`;
  },
});

// ---------- per-theme / per-brand config ----------

const themeSources = (themeName) => [
  `${SD_ROOT}/tokens-dtcg/tier-1/*.json`,
  `${SD_ROOT}/tokens-dtcg/tier-2/*.json`,
  `${SD_ROOT}/tokens-dtcg/tier-2/theme/${themeName}/*.json`,
  `${SD_ROOT}/tokens-dtcg/tier-3/theme/${themeName}/*.json`,
];

const themeConfig = (themeName, { withCore = false } = {}) => {
  const scssFiles = [
    {
      destination: `tokens-${themeName}.scss`,
      format: 'tokens',
      options: { outputReferences: true },
    },
  ];
  if (withCore) {
    // Mirror v3: variables.scss is emitted from each theme build,
    // overwriting (output is theme-independent — only breakpoints —
    // so the overwrite is idempotent).
    scssFiles.push({
      destination: '../../core/variables.scss',
      format: 'al-scss-vars',
      options: { outputReferences: true },
    });
  }
  const platforms = {
    css: {
      transformGroup: 'css-v3-shape',
      buildPath: 'dist-v5/css/theme/',
      files: [
        {
          destination: `tokens-${themeName}.css`,
          format: 'tokens',
          options: { outputReferences: true },
        },
      ],
    },
    scss: {
      transformGroup: 'scss-v3-shape',
      buildPath: 'dist-v5/scss/theme/',
      files: scssFiles,
    },
  };
  if (withCore) {
    platforms.json = {
      transformGroup: 'scss-v3-shape',
      buildPath: 'dist-v5/',
      files: [
        {
          destination: 'tokens.json',
          format: 'al-json-flat',
          options: { outputReferences: true },
        },
      ],
    };
  }
  return {
    usesDtcg: true,
    log: { verbosity: 'silent', warnings: 'disabled' },
    source: themeSources(themeName),
    platforms,
  };
};

const brandIncludes = (themeName) => [
    `${SD_ROOT}/tokens-dtcg/tier-1/*.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/animations.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/borders.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/icons.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/layout.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/opacity.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/shadows.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/spacing.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/typography.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/theme/${themeName}/*.json`,
    `${SD_ROOT}/tokens-dtcg/tier-3/theme/${themeName}/*.json`,
];

// Brand deltas only — the full token surface comes from `brandIncludes` above.
//
// A `tokens-dtcg/tier-3/brand/${brandName}/*.json` glob used to sit here and
// matched nothing: `styles/tokens-dtcg/tier-3/` has never had a `brand/`
// directory.
// Removed rather than materialized so a tier-3 brand layer is re-added
// deliberately — if brand identities need one, add the authored files under
// `styles/tokens-dtcg/tier-3/brand/<brand>/` AND restore the glob here together.
//
// PER-MODE BRAND COLOR DELTAS (spec 2026-08-20-southleft-example-app, T9
// round 2 — see `.altitude/BRANDS.md` §1/§6 update). A brand's `colors.json`
// is theme-INDEPENDENT by construction — the same file builds against both
// `light` and `dark` includes (see `brands` array below), so a literal value
// written there resolves identically in both builds and gets classified
// `invariant` by the delta-splitter two screens down. That's correct for an
// accent hue (southleft's red is red in both modes) but wrong for a NEUTRAL
// canvas that must itself flip warm-dark ↔ warm-light with the mode — no
// single theme-independent value can do that.
// `tier-2/brand/<brand>/mode/<theme>/colors.json` (note: nested one level so
// the existing `tier-2/brand/<brand>/*.json` glob — intentionally
// non-recursive, matching `brandIncludes`'s own `tier-2/theme/${themeName}/
// *.json` pattern — never touches it) is loaded ADDITIONALLY, only for that
// theme's build. Because the two theme builds now genuinely diverge on these
// properties, the existing delta-splitter (unchanged) correctly classifies
// them `perMode` and routes them into the `:host([brand='<brand>']
// [mode='<theme>'])` block (0,3,0) — which already outranks the mode axis's
// own `:host([mode])` block (0,2,0) restating `background.default` /
// `content.default` (BRANDS.md §5's "mode owns these" note predates any
// brand having a reason to override them; the 0,3,0 selector was always
// there for exactly this case). No other brand file, the delta-splitter, or
// the `theme.scss` `@use` order needed to change.
const brandSources = (brandName, themeName) => {
  const files = [`${SD_ROOT}/tokens-dtcg/tier-2/brand/${brandName}/*.json`];
  if (themeName) {
    const modeFile = `${SD_ROOT}/tokens-dtcg/tier-2/brand/${brandName}/mode/${themeName}/colors.json`;
    if (existsSync(modeFile)) files.push(modeFile);
  }
  return files;
};

const brandConfig = (themeName, brandName) => ({
  usesDtcg: true,
  log: { verbosity: 'verbose' },
  include: brandIncludes(themeName),
  source: brandSources(brandName, themeName),
  platforms: {
    css: {
      transformGroup: 'css-v3-shape',
      buildPath: `dist-v5/css/brand/`,
      files: [
        {
          destination: `tokens-${brandName}-${themeName}.css`,
          format: 'tokens',
          options: { outputReferences: true },
        },
      ],
    },
    scss: {
      transformGroup: 'scss-v3-shape',
      buildPath: `dist-v5/scss/brand/`,
      files: [
        {
          destination: `tokens-${brandName}-${themeName}.scss`,
          format: 'tokens',
          options: { outputReferences: true },
        },
      ],
    },
  },
});

// ---------- scoped `:host` emission (R2) ----------
//
// WHY THIS EXISTS. `<al-theme brand mode density contrast>` has always typed a
// `brand` attribute and `components/theme/theme.scss` has never had a rule
// that reads it, so `brand` was inert while CLAUDE.md, MIGRATION.md and
// `.changeset/v2-major.md` all advertised working multi-brand pages. These
// partials are the missing half.
//
// WHY DELTAS. `:host` blocks are compiled into `<al-theme>`'s `static styles`,
// so their bytes ship in the JS bundle. Restating each brand x mode bundle in
// full costs 104,962 B across the matrix — 3.2x the 33,309 B that CI's
// `baselines-bundle` job allows (`.github/workflows/v2-checks.yml:191-220`).
// A host INHERITS every `--al-*` it does not restate, so the delta computes
// the identical value for ~15 KB. Cost of the choice, stated plainly:
// `<al-theme>` COMPOSES ON TOP of a base token sheet, it does not replace one.
// A page with no `:root` bundle loaded gets brand deltas resolving against
// nothing.
//
// WHY THE BRAND BLOCKS ARE SPLIT IN TWO. `<al-theme>` does not reflect its
// properties, so `<al-theme brand="southleft">` with no `mode` attribute matches
// no `[mode]` selector. Splitting each brand delta into
//   * `:host([brand='x'])`          — the part that is identical in every mode
//                                     the brand builds AND is not a property
//                                     the base theme varies by mode, and
//   * `:host([brand='x'][mode='y'])` — the remainder
// means a brand always contributes its mode-independent identity (type ramp,
// radii, spacing, border weights) even with no `mode` set, and never asserts a
// colour that contradicts the mode actually in force. Measured: southleft
// needs no per-mode block at all today.
//
// SPECIFICITY. `:host([brand][mode])` is exactly 0,3,0 and `:host([brand])` /
// `:host([mode])` are 0,2,0 — the budget `scripts/check-css-layers.js` enforces
// is 0,3,0, so the brand x mode form sits on the ceiling with zero headroom. A
// third attribute is not available; that is why density/contrast stay
// hand-written in theme.scss. The checker lints these generated files directly
// (it used to only read `components/<name>/<name>.scss`, which `@use` hides).

const HOST_DIR = 'dist-v5/scss/host';

/** Parse `--name: value;` out of an emitted artifact. */
async function readDeclarations(file) {
  const text = await fs.readFile(file, 'utf8');
  const map = new Map();
  for (const line of text.split('\n')) {
    const m = line.match(/^\s*(--[A-Za-z0-9-]+):\s*(.*);\s*$/);
    if (m) map.set(m[1], m[2]);
  }
  return map;
}

function hostPlatform(destination, selector, { onlyNames = null, omitEqualTo = null }) {
  return {
    scss: {
      transformGroup: 'scss-v3-shape',
      buildPath: `${HOST_DIR}/`,
      files: [
        {
          destination,
          format: 'tokens',
          options: { outputReferences: true, selector, layer: 'al.theme', onlyNames, omitEqualTo },
        },
      ],
    },
  };
}

// ---------- main ----------

async function build() {
  // Run from the workspace root so `buildPath: 'dist-v5/...'` lands under
  // libs/al-web-components/styles/dist-v5/.
  process.chdir(SD_ROOT);

  // Clean previous v5 output so deletions surface.
  await fs.rm('dist-v5', { recursive: true, force: true });

  const themes = ['light', 'dark'];
  const brands = [
    // `altitude` is the default brand (`<al-theme brand>` in components/theme/theme.ts).
    // It builds in BOTH modes because the base theme output it used to stand in for
    // exists in both. southleft used to be dark-only ("ink"); spec
    // 2026-08-20-southleft-example-app adds its light "paper" mode — the brand
    // token deltas (colour, radius, border-width, shadow, typography) are
    // theme-independent, so the SAME `tier-2/brand/southleft/*.json` files now
    // build against both base themes.
    { theme: 'light', brand: 'altitude' },
    { theme: 'dark', brand: 'altitude' },
    { theme: 'dark', brand: 'southleft' },
    { theme: 'light', brand: 'southleft' },
  ];

  // Per-theme css + scss tokens files. v3 emits variables.scss + tokens.json
  // from each theme build to the same path, so the *last* build wins. v3
  // order is light → dark, so dark is the surviving copy on disk. Match that.
  for (const theme of themes) {
    const sd = new StyleDictionary(themeConfig(theme, { withCore: theme === 'dark' }));
    await sd.buildAllPlatforms();
  }

  // Per-brand css + scss tokens files.
  for (const { theme, brand } of brands) {
    const sd = new StyleDictionary(brandConfig(theme, brand));
    await sd.buildAllPlatforms();
  }

  // ---- scoped `:host` partials for <al-theme> (R2) ----
  //
  // Derived from the artifacts the two loops above just wrote, so a host block
  // can never disagree with the `:root` block it is a delta of. Emitted last
  // for that reason.

  const themeDecls = Object.fromEntries(
    await Promise.all(
      themes.map(async (t) => [t, await readDeclarations(`dist-v5/css/theme/tokens-${t}.css`)])
    )
  );

  // Properties the BASE theme varies by mode (23 today: the default
  // background/content/border surface, the shadow tint, and the six
  // `--al-box-shadow-N` literals that recompute from it). A brand override of
  // one of these has to live in a `[mode]`-qualified block or it would assert
  // a dark value on a light host.
  const modeVarying = new Set();
  for (const t of themes) {
    for (const [name, value] of themeDecls[t]) {
      if (themes.some((o) => themeDecls[o].get(name) !== value)) modeVarying.add(name);
    }
  }

  const emitted = [];
  async function emitHost(destination, selector, narrowing, theme, brand) {
    const cfg = brand
      ? { include: brandIncludes(theme), source: brandSources(brand, theme) }
      : { source: themeSources(theme) };
    const sd = new StyleDictionary({
      usesDtcg: true,
      log: { verbosity: 'silent', warnings: 'disabled' },
      ...cfg,
      platforms: hostPlatform(destination, selector, narrowing),
    });
    await sd.buildAllPlatforms();
    emitted.push(destination);
  }

  // 1. Mode. Symmetric deltas: each block restates exactly the properties that
  //    differ between the two base themes, so `<al-theme mode="light">` lands
  //    on light values whichever base sheet the page loaded, and
  //    `<al-theme mode="dark">` on a dark page is a no-op restatement.
  //    This replaces the two hardcoded hexes theme.scss used to carry (R4) —
  //    those disagreed with the generated tokens and, sitting on the element,
  //    beat them.
  for (const theme of themes) {
    const other = themes.find((t) => t !== theme);
    await emitHost(
      `tokens-mode-${theme}.scss`,
      `:host([mode='${theme}'])`,
      { omitEqualTo: themeDecls[other] },
      theme,
      null
    );
  }

  // 2. Brand. Split per the header comment. `altitude` is the neutral
  //    reference (`.altitude/BRANDS.md` §6 rule 8) and its bundles are
  //    byte-identical to the base theme, so its delta is empty and no file is
  //    written — an empty rule would be dead weight, and its absence is the
  //    assertion that altitude really is neutral.
  const byBrand = new Map();
  for (const { theme, brand } of brands) {
    if (!byBrand.has(brand)) byBrand.set(brand, []);
    byBrand.get(brand).push(theme);
  }

  for (const [brand, brandModes] of byBrand) {
    const deltas = new Map();
    for (const theme of brandModes) {
      const bundle = await readDeclarations(`dist-v5/css/brand/tokens-${brand}-${theme}.css`);
      const d = new Map();
      for (const [name, value] of bundle) {
        if (themeDecls[theme].get(name) !== value) d.set(name, value);
      }
      deltas.set(theme, d);
    }
    const allNames = new Set([...deltas.values()].flatMap((d) => [...d.keys()]));
    const invariant = new Set();
    const perMode = new Set();
    for (const name of allNames) {
      const first = deltas.get(brandModes[0]).get(name);
      const sameInEveryMode = brandModes.every((t) => deltas.get(t).get(name) === first);
      if (sameInEveryMode && !modeVarying.has(name)) invariant.add(name);
      else perMode.add(name);
    }

    if (invariant.size > 0) {
      await emitHost(
        `tokens-brand-${brand}.scss`,
        `:host([brand='${brand}'])`,
        { onlyNames: invariant, omitEqualTo: themeDecls[brandModes[0]] },
        brandModes[0],
        brand
      );
    }
    for (const theme of brandModes) {
      const names = new Set([...perMode].filter((n) => deltas.get(theme).has(n)));
      if (names.size === 0) continue;
      await emitHost(
        `tokens-brand-${brand}-${theme}.scss`,
        `:host([brand='${brand}'][mode='${theme}'])`,
        { onlyNames: names, omitEqualTo: themeDecls[theme] },
        theme,
        brand
      );
    }
  }

  // 3. The entry point `components/theme/theme.scss` @uses. Order matters for
  //    the two 0,2,0 families: mode first, brand second, so that when a brand
  //    and the base theme both name a property the brand wins. (Today they
  //    never collide — `modeVarying` names are routed to the 0,3,0 blocks —
  //    but the ordering makes that a property of the file, not luck.)
  const order = [
    ...emitted.filter((f) => f.startsWith('tokens-mode-')),
    ...emitted.filter((f) => f.startsWith('tokens-brand-') && f.split('-').length === 3),
    ...emitted.filter((f) => f.startsWith('tokens-brand-') && f.split('-').length > 3),
  ];
  await fs.writeFile(
    `${HOST_DIR}/_index.scss`,
    `${comment}// Scoped token blocks for <al-theme>. Generated by styles/tokens-config.v5.mjs.\n` +
      `// Loaded by components/theme/theme.scss; see that file and the emitter's\n` +
      `// "scoped \`:host\` emission" comment for the delta/specificity rationale.\n` +
      order.map((f) => `@use './${f}';`).join('\n') +
      '\n'
  );

  console.log(
    `[tokens:v5] build complete → libs/al-web-components/styles/dist-v5/ ` +
      `(${order.length} scoped host partial(s))`
  );
}

build().catch((err) => {
  console.error('[tokens:v5] FAIL:', err);
  process.exit(1);
});
