// T1.1 — Style Dictionary v5 parallel pipeline.
//
// Runs alongside the v3 pipeline (`tokens-config.js`). Reads DTCG source
// from `styles/tokens-dtcg/` and emits CSS/SCSS/JSON to
// `styles/dist-v5/` so the diff against v3's `styles/dist/` is the
// byte-comparability check the plan demands.
//
// Acceptance (per T1.1):
//   yarn build:tokens:v5 emits CSS whose `--al-*` variable set is
//   byte-identical to v3 output.

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';
import { usesReferences, getReferences } from 'style-dictionary/utils';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SD_ROOT = __dirname; // .../libs/al-web-components/styles
const WORKSPACE_ROOT = path.resolve(SD_ROOT, '..'); // .../libs/al-web-components

const themePrefix = 'al';
const themeFontWeightRegular = '400';
const themeFontWeightBold = '600';
const themeFontBaseSize = 16;
const themeSpaceBaseSize = 16;
const themeFontFamilyFallback = 'sans-serif';
const comment = '\n\n/* This file is auto-generated by Style Dictionary. Do not edit directly. */\n';

// ---------- helpers (ported from v3 verbatim) ----------

function formatBoxShadowValue(value) {
  if (Array.isArray(value)) {
    return value
      .map((s) => `${s.x}px ${s.y}px ${s.blur}px ${s.spread}px ${s.color}`)
      .join(', ');
  }
  return `${value.x}px ${value.y}px ${value.blur}px ${value.spread}px ${value.color}`;
}

function formatFontWeightValue(value) {
  return value === 'Bold' ? themeFontWeightBold : themeFontWeightRegular;
}

function formatTypographyValue(value) {
  const fontSize = `${parseFloat(value.fontSize) / themeFontBaseSize}rem`;
  const lineHeight = `${parseFloat(value.lineHeight) / themeFontBaseSize}rem`;
  return `${formatFontWeightValue(value.fontWeight)} ${fontSize}/${lineHeight} ${value.fontFamily}, ${themeFontFamilyFallback}`;
}

function formatSpaceValue(value) {
  return `${parseFloat(value) / themeSpaceBaseSize}rem`;
}

// SD v5 stores DTCG values under `$value` when `usesDtcg: true`. Wrap the
// token access so the rest of the format code can stay structurally close
// to the v3 implementation.
function tokenValue(token) {
  return '$value' in token ? token.$value : token.value;
}
function tokenOriginalValue(token) {
  return '$value' in token.original ? token.original.$value : token.original.value;
}

// ---------- custom transform groups (mirror v3 — no DTCG shorthand transforms) ----------
//
// SD v5's `css`/`scss` groups inject `typography/css/shorthand`,
// `shadow/css/shorthand`, etc. that coerce composite tokens into CSS strings
// BEFORE our format runs. v3 had no such transforms — our custom formatters
// (`formatTypographyValue`, `formatBoxShadowValue`) need the raw value
// objects. Register replacement groups that strip the shorthand transforms.

StyleDictionary.registerTransformGroup({
  name: 'css-v3-shape',
  transforms: [
    'attribute/cti',
    'name/kebab',
    'time/seconds',
    'html/icon',
    'size/rem',
    'color/css',
    'asset/url',
    'cubicBezier/css',
  ],
});
StyleDictionary.registerTransformGroup({
  name: 'scss-v3-shape',
  transforms: [
    'attribute/cti',
    'name/kebab',
    'time/seconds',
    'html/icon',
    'size/rem',
    'color/css',
    'asset/url',
    'cubicBezier/css',
  ],
});

// ---------- custom formats (ported from v3 to v5 API) ----------

/**
 * The one place a declaration list becomes a CSS rule.
 *
 * `selector` and `layer` are FILE OPTIONS, not literals (R1 of
 * `2026-07-28-scoped-token-emission-brand-wiring`). The defaults —
 * `':root'` and no layer — reproduce the pre-existing output byte for byte,
 * which is the entire back-compat strategy: ten apps, two Storybook previews
 * and ten SCSS files consume the flat `:root` artifacts and none of them had
 * to change.
 */
function renderRule(pairs, { selector = ':root', layer = null } = {}) {
  const indent = layer ? '    ' : '  ';
  const decls = pairs.map(([name, value]) => `${indent}${name}: ${value};`).join('\n');
  if (!layer) return `${selector} {\n${decls}\n}\n`;
  return `@layer ${layer} {\n  ${selector} {\n${decls}\n  }\n}\n`;
}

StyleDictionary.registerFormat({
  name: 'tokens',
  format: ({ dictionary, options }) => {
    const pairs = dictionary.allTokens
      .filter(
        (token) =>
          !token.name.endsWith('-italic') &&
          !token.name.endsWith('-underline') &&
          !token.name.includes('breakpoint')
      )
      .map((token) => {
        let name;
        let value = tokenValue(token);

        if (token.name.includes('font-weight')) {
          name = token.name;
          value = formatFontWeightValue(tokenValue(token));
        } else if (token.name.includes('typography')) {
          name = token.name.endsWith('-regular') ? token.name.replace('-regular', '') : token.name;
          value = formatTypographyValue(tokenValue(token));
        } else if (token.name.includes('box-shadow')) {
          name = token.name;
          value = formatBoxShadowValue(tokenValue(token));
        } else if (!token.name.includes('base') && token.name.includes('space')) {
          name = token.name;
          value = formatSpaceValue(tokenValue(token));
        } else {
          name = token.name;
          value = tokenValue(token);
        }

        if (token.name.includes('theme') && options.outputReferences) {
          const origValue = tokenOriginalValue(token);
          if (usesReferences(origValue)) {
            const refs = getReferences(origValue, dictionary.tokens, { usesDtcg: true });
            refs.forEach((ref) => {
              const refName = ref.name.endsWith('-regular') ? ref.name.replace('-regular', '') : ref.name;
              value = `var(--${themePrefix}-${refName})`;
            });
          }
        }
        return [`--${themePrefix}-${name}`, value];
      });

    // R2 — scoped (host) emission is a DELTA, not a copy.
    //
    // `options.onlyNames` (a Set of `--al-…` names) and `options.omitEqualTo`
    // (a Map of `--al-…` -> value read back from an already-emitted `:root`
    // artifact) narrow the declaration list to exactly what the host has to
    // restate. Both are absent for every `:root` file, so those keep emitting
    // the full surface unchanged.
    //
    // Deltas rather than full 17 KB copies because a host INHERITS the base
    // `:root` values through the shadow boundary — restating them costs
    // ~105 KB across the matrix (3.2x the CI bundle allowance) to compute the
    // same thing. See the spec's T9 measurement.
    const only = options.onlyNames ?? null;
    const base = options.omitEqualTo ?? null;
    const kept = pairs.filter(
      ([name, value]) =>
        (!only || only.has(name)) && (!base || base.get(name) !== String(value))
    );

    return comment + renderRule(kept, { selector: options.selector, layer: options.layer });
  },
});

StyleDictionary.registerFormat({
  name: 'al-scss-vars',
  format: ({ dictionary, options }) => {
    const breakpointVariables = dictionary.allTokens
      .filter((token) => token.name.includes('breakpoint'))
      .map((token) => {
        let value = JSON.parse(JSON.stringify(tokenValue(token)));
        const origValue = tokenOriginalValue(token);
        if (options.outputReferences && usesReferences(origValue)) {
          const refs = getReferences(origValue, dictionary.tokens, { usesDtcg: true });
          value = refs.map((ref) => `breakpoint-${ref.name}`).join(', ');
        }
        return `$${themePrefix}-${token.name}: ${value};`;
      })
      .join('\n');

    const themeDeclaration = `$${themePrefix}-theme-prefix: '${themePrefix}';\n`;
    return comment + themeDeclaration + breakpointVariables;
  },
});

StyleDictionary.registerFormat({
  name: 'al-json-flat',
  format: ({ dictionary, options }) => {
    const variables = dictionary.allTokens
      .filter((token) => !token.name.endsWith('-italic') && !token.name.endsWith('-underline'))
      .map((token, index, array) => {
        let name;
        let value;
        if (token.name.includes('font-weight')) {
          name = token.name;
          value = formatFontWeightValue(tokenValue(token));
        } else if (token.name.includes('typography')) {
          name = token.name.endsWith('-regular') ? token.name.replace('-regular', '') : token.name;
          value = formatTypographyValue(tokenValue(token));
        } else if (token.name.includes('box-shadow')) {
          name = token.name;
          value = formatBoxShadowValue(tokenValue(token));
        } else {
          name = token.name;
          value = tokenValue(token);
        }

        if (token.name.includes('theme') && options.outputReferences) {
          const origValue = tokenOriginalValue(token);
          if (usesReferences(origValue)) {
            const refs = getReferences(origValue, dictionary.tokens, { usesDtcg: true });
            refs.forEach((ref) => {
              const refName = ref.name.endsWith('-regular') ? ref.name.replace('-regular', '') : ref.name;
              value = `var(--${themePrefix}-${refName})`;
            });
          }
        }
        const comma = index === array.length - 1 ? '' : ',';
        return `  "${themePrefix}-${name}": "${value}"${comma}`;
      })
      .join('\n');

    return `{\n${variables}\n}`;
  },
});

// ---------- per-theme / per-brand config ----------

const themeSources = (themeName) => [
  `${SD_ROOT}/tokens-dtcg/tier-1/*.json`,
  `${SD_ROOT}/tokens-dtcg/tier-2/*.json`,
  `${SD_ROOT}/tokens-dtcg/tier-2/theme/${themeName}/*.json`,
  `${SD_ROOT}/tokens-dtcg/tier-3/theme/${themeName}/*.json`,
];

const themeConfig = (themeName, { withCore = false } = {}) => {
  const scssFiles = [
    {
      destination: `tokens-${themeName}.scss`,
      format: 'tokens',
      options: { outputReferences: true },
    },
  ];
  if (withCore) {
    // Mirror v3: variables.scss is emitted from each theme build,
    // overwriting (output is theme-independent — only breakpoints —
    // so the overwrite is idempotent).
    scssFiles.push({
      destination: '../../core/variables.scss',
      format: 'al-scss-vars',
      options: { outputReferences: true },
    });
  }
  const platforms = {
    css: {
      transformGroup: 'css-v3-shape',
      buildPath: 'dist-v5/css/theme/',
      files: [
        {
          destination: `tokens-${themeName}.css`,
          format: 'tokens',
          options: { outputReferences: true },
        },
      ],
    },
    scss: {
      transformGroup: 'scss-v3-shape',
      buildPath: 'dist-v5/scss/theme/',
      files: scssFiles,
    },
  };
  if (withCore) {
    platforms.json = {
      transformGroup: 'scss-v3-shape',
      buildPath: 'dist-v5/',
      files: [
        {
          destination: 'tokens.json',
          format: 'al-json-flat',
          options: { outputReferences: true },
        },
      ],
    };
  }
  return {
    usesDtcg: true,
    log: { verbosity: 'silent', warnings: 'disabled' },
    source: themeSources(themeName),
    platforms,
  };
};

const brandIncludes = (themeName) => [
    `${SD_ROOT}/tokens-dtcg/tier-1/*.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/animations.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/borders.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/icons.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/layout.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/opacity.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/shadows.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/spacing.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/typography.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/theme/${themeName}/*.json`,
    `${SD_ROOT}/tokens-dtcg/tier-3/theme/${themeName}/*.json`,
];

// Brand deltas only — the full token surface comes from `brandIncludes` above.
//
// A `tokens-dtcg/tier-3/brand/${brandName}/*.json` glob used to sit here and
// matched nothing: neither `styles/tokens/tier-3/` (hand-authored) nor
// `styles/tokens-dtcg/tier-3/` (generated by scripts/convert-tokens-to-dtcg.js,
// which mirrors files, not empty dirs) has ever had a `brand/` directory.
// Removed rather than materialized so a tier-3 brand layer is re-added
// deliberately — if brand identities need one, add the authored files under
// `styles/tokens/tier-3/brand/<brand>/` AND restore the glob here together.
const brandSources = (brandName) => [`${SD_ROOT}/tokens-dtcg/tier-2/brand/${brandName}/*.json`];

const brandConfig = (themeName, brandName) => ({
  usesDtcg: true,
  log: { verbosity: 'verbose' },
  include: brandIncludes(themeName),
  source: brandSources(brandName),
  platforms: {
    css: {
      transformGroup: 'css-v3-shape',
      buildPath: `dist-v5/css/brand/`,
      files: [
        {
          destination: `tokens-${brandName}-${themeName}.css`,
          format: 'tokens',
          options: { outputReferences: true },
        },
      ],
    },
    scss: {
      transformGroup: 'scss-v3-shape',
      buildPath: `dist-v5/scss/brand/`,
      files: [
        {
          destination: `tokens-${brandName}-${themeName}.scss`,
          format: 'tokens',
          options: { outputReferences: true },
        },
      ],
    },
  },
});

// ---------- scoped `:host` emission (R2) ----------
//
// WHY THIS EXISTS. `<al-theme brand mode density contrast>` has always typed a
// `brand` attribute and `components/theme/theme.scss` has never had a rule
// that reads it, so `brand` was inert while CLAUDE.md, MIGRATION.md and
// `.changeset/v2-major.md` all advertised working multi-brand pages. These
// partials are the missing half.
//
// WHY DELTAS. `:host` blocks are compiled into `<al-theme>`'s `static styles`,
// so their bytes ship in the JS bundle. Restating each brand x mode bundle in
// full costs 104,962 B across the matrix — 3.2x the 33,309 B that CI's
// `baselines-bundle` job allows (`.github/workflows/v2-checks.yml:191-220`).
// A host INHERITS every `--al-*` it does not restate, so the delta computes
// the identical value for ~15 KB. Cost of the choice, stated plainly:
// `<al-theme>` COMPOSES ON TOP of a base token sheet, it does not replace one.
// A page with no `:root` bundle loaded gets brand deltas resolving against
// nothing.
//
// WHY THE BRAND BLOCKS ARE SPLIT IN TWO. `<al-theme>` does not reflect its
// properties, so `<al-theme brand="odyssey">` with no `mode` attribute matches
// no `[mode]` selector. Splitting each brand delta into
//   * `:host([brand='x'])`          — the part that is identical in every mode
//                                     the brand builds AND is not a property
//                                     the base theme varies by mode, and
//   * `:host([brand='x'][mode='y'])` — the remainder
// means a brand always contributes its mode-independent identity (type ramp,
// radii, spacing, border weights) even with no `mode` set, and never asserts a
// colour that contradicts the mode actually in force. Measured: northright and
// southleft need no per-mode block at all; odyssey needs 7 declarations.
//
// SPECIFICITY. `:host([brand][mode])` is exactly 0,3,0 and `:host([brand])` /
// `:host([mode])` are 0,2,0 — the budget `scripts/check-css-layers.js` enforces
// is 0,3,0, so the brand x mode form sits on the ceiling with zero headroom. A
// third attribute is not available; that is why density/contrast stay
// hand-written in theme.scss. The checker lints these generated files directly
// (it used to only read `components/<name>/<name>.scss`, which `@use` hides).

const HOST_DIR = 'dist-v5/scss/host';

/** Parse `--name: value;` out of an emitted artifact. */
async function readDeclarations(file) {
  const text = await fs.readFile(file, 'utf8');
  const map = new Map();
  for (const line of text.split('\n')) {
    const m = line.match(/^\s*(--[A-Za-z0-9-]+):\s*(.*);\s*$/);
    if (m) map.set(m[1], m[2]);
  }
  return map;
}

function hostPlatform(destination, selector, { onlyNames = null, omitEqualTo = null }) {
  return {
    scss: {
      transformGroup: 'scss-v3-shape',
      buildPath: `${HOST_DIR}/`,
      files: [
        {
          destination,
          format: 'tokens',
          options: { outputReferences: true, selector, layer: 'al.theme', onlyNames, omitEqualTo },
        },
      ],
    },
  };
}

// ---------- main ----------

async function build() {
  // Run from the workspace root so `buildPath: 'dist-v5/...'` lands under
  // libs/al-web-components/styles/dist-v5/.
  process.chdir(SD_ROOT);

  // Clean previous v5 output so deletions surface.
  await fs.rm('dist-v5', { recursive: true, force: true });

  const themes = ['light', 'dark'];
  const brands = [
    // `altitude` is the default brand (`<al-theme brand>` in components/theme/theme.ts).
    // It builds in BOTH modes because the base theme output it used to stand in for
    // exists in both; southleft/odyssey are deliberately dark-only.
    { theme: 'light', brand: 'altitude' },
    { theme: 'dark', brand: 'altitude' },
    { theme: 'dark', brand: 'southleft' },
    { theme: 'light', brand: 'northright' },
    { theme: 'dark', brand: 'northright' },
    { theme: 'dark', brand: 'odyssey' },
  ];

  // Per-theme css + scss tokens files. v3 emits variables.scss + tokens.json
  // from each theme build to the same path, so the *last* build wins. v3
  // order is light → dark, so dark is the surviving copy on disk. Match that.
  for (const theme of themes) {
    const sd = new StyleDictionary(themeConfig(theme, { withCore: theme === 'dark' }));
    await sd.buildAllPlatforms();
  }

  // Per-brand css + scss tokens files.
  for (const { theme, brand } of brands) {
    const sd = new StyleDictionary(brandConfig(theme, brand));
    await sd.buildAllPlatforms();
  }

  // ---- scoped `:host` partials for <al-theme> (R2) ----
  //
  // Derived from the artifacts the two loops above just wrote, so a host block
  // can never disagree with the `:root` block it is a delta of. Emitted last
  // for that reason.

  const themeDecls = Object.fromEntries(
    await Promise.all(
      themes.map(async (t) => [t, await readDeclarations(`dist-v5/css/theme/tokens-${t}.css`)])
    )
  );

  // Properties the BASE theme varies by mode (23 today: the default
  // background/content/border surface, the shadow tint, and the six
  // `--al-box-shadow-N` literals that recompute from it). A brand override of
  // one of these has to live in a `[mode]`-qualified block or it would assert
  // a dark value on a light host.
  const modeVarying = new Set();
  for (const t of themes) {
    for (const [name, value] of themeDecls[t]) {
      if (themes.some((o) => themeDecls[o].get(name) !== value)) modeVarying.add(name);
    }
  }

  const emitted = [];
  async function emitHost(destination, selector, narrowing, theme, brand) {
    const cfg = brand
      ? { include: brandIncludes(theme), source: brandSources(brand) }
      : { source: themeSources(theme) };
    const sd = new StyleDictionary({
      usesDtcg: true,
      log: { verbosity: 'silent', warnings: 'disabled' },
      ...cfg,
      platforms: hostPlatform(destination, selector, narrowing),
    });
    await sd.buildAllPlatforms();
    emitted.push(destination);
  }

  // 1. Mode. Symmetric deltas: each block restates exactly the properties that
  //    differ between the two base themes, so `<al-theme mode="light">` lands
  //    on light values whichever base sheet the page loaded, and
  //    `<al-theme mode="dark">` on a dark page is a no-op restatement.
  //    This replaces the two hardcoded hexes theme.scss used to carry (R4) —
  //    those disagreed with the generated tokens and, sitting on the element,
  //    beat them.
  for (const theme of themes) {
    const other = themes.find((t) => t !== theme);
    await emitHost(
      `tokens-mode-${theme}.scss`,
      `:host([mode='${theme}'])`,
      { omitEqualTo: themeDecls[other] },
      theme,
      null
    );
  }

  // 2. Brand. Split per the header comment. `altitude` is the neutral
  //    reference (`.altitude/BRANDS.md` §6 rule 8) and its bundles are
  //    byte-identical to the base theme, so its delta is empty and no file is
  //    written — an empty rule would be dead weight, and its absence is the
  //    assertion that altitude really is neutral.
  const byBrand = new Map();
  for (const { theme, brand } of brands) {
    if (!byBrand.has(brand)) byBrand.set(brand, []);
    byBrand.get(brand).push(theme);
  }

  for (const [brand, brandModes] of byBrand) {
    const deltas = new Map();
    for (const theme of brandModes) {
      const bundle = await readDeclarations(`dist-v5/css/brand/tokens-${brand}-${theme}.css`);
      const d = new Map();
      for (const [name, value] of bundle) {
        if (themeDecls[theme].get(name) !== value) d.set(name, value);
      }
      deltas.set(theme, d);
    }
    const allNames = new Set([...deltas.values()].flatMap((d) => [...d.keys()]));
    const invariant = new Set();
    const perMode = new Set();
    for (const name of allNames) {
      const first = deltas.get(brandModes[0]).get(name);
      const sameInEveryMode = brandModes.every((t) => deltas.get(t).get(name) === first);
      if (sameInEveryMode && !modeVarying.has(name)) invariant.add(name);
      else perMode.add(name);
    }

    if (invariant.size > 0) {
      await emitHost(
        `tokens-brand-${brand}.scss`,
        `:host([brand='${brand}'])`,
        { onlyNames: invariant, omitEqualTo: themeDecls[brandModes[0]] },
        brandModes[0],
        brand
      );
    }
    for (const theme of brandModes) {
      const names = new Set([...perMode].filter((n) => deltas.get(theme).has(n)));
      if (names.size === 0) continue;
      await emitHost(
        `tokens-brand-${brand}-${theme}.scss`,
        `:host([brand='${brand}'][mode='${theme}'])`,
        { onlyNames: names, omitEqualTo: themeDecls[theme] },
        theme,
        brand
      );
    }
  }

  // 3. The entry point `components/theme/theme.scss` @uses. Order matters for
  //    the two 0,2,0 families: mode first, brand second, so that when a brand
  //    and the base theme both name a property the brand wins. (Today they
  //    never collide — `modeVarying` names are routed to the 0,3,0 blocks —
  //    but the ordering makes that a property of the file, not luck.)
  const order = [
    ...emitted.filter((f) => f.startsWith('tokens-mode-')),
    ...emitted.filter((f) => f.startsWith('tokens-brand-') && f.split('-').length === 3),
    ...emitted.filter((f) => f.startsWith('tokens-brand-') && f.split('-').length > 3),
  ];
  await fs.writeFile(
    `${HOST_DIR}/_index.scss`,
    `${comment}// Scoped token blocks for <al-theme>. Generated by styles/tokens-config.v5.mjs.\n` +
      `// Loaded by components/theme/theme.scss; see that file and the emitter's\n` +
      `// "scoped \`:host\` emission" comment for the delta/specificity rationale.\n` +
      order.map((f) => `@use './${f}';`).join('\n') +
      '\n'
  );

  console.log(
    `[tokens:v5] build complete → libs/al-web-components/styles/dist-v5/ ` +
      `(${order.length} scoped host partial(s))`
  );
}

build().catch((err) => {
  console.error('[tokens:v5] FAIL:', err);
  process.exit(1);
});
