// T1.1 — Style Dictionary v5 parallel pipeline.
//
// Runs alongside the v3 pipeline (`tokens-config.js`). Reads DTCG source
// from `styles/tokens-dtcg/` and emits CSS/SCSS/JSON to
// `styles/dist-v5/` so the diff against v3's `styles/dist/` is the
// byte-comparability check the plan demands.
//
// Acceptance (per T1.1):
//   pnpm build:tokens emits CSS whose `--al-*` variable set is
//   byte-identical to v3 output.

import { promises as fs } from 'node:fs';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';
import { usesReferences, getReferences } from 'style-dictionary/utils';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SD_ROOT = __dirname; // .../libs/al-web-components/styles
const WORKSPACE_ROOT = path.resolve(SD_ROOT, '..'); // .../libs/al-web-components

const themePrefix = 'al';
const themeFontWeightRegular = '400';
const themeFontWeightMedium = '500';
const themeFontWeightSemibold = '600';
const themeFontWeightBold = '700';

/*
 * Named weight -> CSS numeric. This used to be a BINARY: `'Bold' ? 600 : 400`,
 * so the pipeline could express exactly two weights and every other name
 * silently collapsed to 400 — a token authored as "Medium" emitted 400 and gave
 * no warning that it had been flattened. The v2 canvas uses three (400 body,
 * 500 chips and the mono metadata face, 600 controls and headings), so the map
 * is explicit.
 *
 * 2026-09-01: SemiBold added and Bold moved 600 -> 700, to match the Figma
 * file, which carries both as distinct faces across all 60 text styles. What
 * code called "Bold" always emitted 600 — semibold — so every preset that
 * rendered at 600 was renamed to `semibold` in the same change and a genuine
 * 700 `bold` added beside it. Renaming without remapping (or the reverse)
 * would silently restyle 29 call sites.
 *
 * The fallback no longer swallows a typo. An unknown name still degrades to
 * regular so a build cannot fail on one token, but it now says so — the
 * previous silent collapse is exactly how "Medium" emitted 400 unnoticed.
 */
const FONT_WEIGHTS = {
  Regular: themeFontWeightRegular,
  Medium: themeFontWeightMedium,
  SemiBold: themeFontWeightSemibold,
  Bold: themeFontWeightBold,
};
const themeFontBaseSize = 16;
const themeSpaceBaseSize = 16;
const themeFontFamilyFallback = 'sans-serif';
const comment = '\n\n/* This file is auto-generated by Style Dictionary. Do not edit directly. */\n';

// ---------- helpers (ported from v3 verbatim) ----------

function formatBoxShadowValue(value) {
  if (Array.isArray(value)) {
    return value
      .map((s) => `${s.x}px ${s.y}px ${s.blur}px ${s.spread}px ${s.color}`)
      .join(', ');
  }
  return `${value.x}px ${value.y}px ${value.blur}px ${value.spread}px ${value.color}`;
}

const unknownFontWeights = new Set();
function formatFontWeightValue(value) {
  const mapped = FONT_WEIGHTS[value];
  if (mapped === undefined && !unknownFontWeights.has(value)) {
    unknownFontWeights.add(value);
    console.warn(`[tokens:v5] unknown font weight "${value}" -> falling back to ${themeFontWeightRegular}. Add it to FONT_WEIGHTS.`);
  }
  return mapped ?? themeFontWeightRegular;
}

function formatTypographyValue(value) {
  const fontSize = `${parseFloat(value.fontSize) / themeFontBaseSize}rem`;
  const lineHeight = `${parseFloat(value.lineHeight) / themeFontBaseSize}rem`;
  return `${formatFontWeightValue(value.fontWeight)} ${fontSize}/${lineHeight} ${value.fontFamily}, ${themeFontFamilyFallback}`;
}

/**
 * The composite typography token authors FIVE sub-values; the CSS `font`
 * shorthand can only carry three of them. `letterSpacing` and `textDecoration`
 * are not `font` sub-properties at all, so they were silently dropped on the
 * floor - every `letterSpacing` the designers authored was inert.
 * `formatLetterSpacingValue` is half of putting them back.
 *
 * Two things to know:
 *
 * 1. UNIT. Figma (and therefore
 *    `tier-1/typography.json`) authors letter-spacing as a PERCENTAGE of the
 *    font size. CSS `letter-spacing` takes a `<length>` and rejects `%`
 *    outright - emitting `letter-spacing: 1%` would produce a declaration the
 *    parser discards, i.e. the same inert result by a longer route. 1% of the
 *    font size is exactly `0.01em`, so `% -> em` is lossless.
 *
 * 2. ZERO IS STILL EMITTED, as the CSS keyword `normal`. The first cut skipped
 *    the 20 presets whose authored tracking is zero, on the grounds that
 *    `0em` is just the CSS initial value and emitting it is noise. That was
 *    wrong, and `scripts/check-token-usage.mjs` said so: the mixins then read
 *    `var(--al-theme-typography-body-md-letter-spacing, normal)` against a
 *    name the pipeline never emitted, which is the tool's PHANTOM case - the
 *    hardcoded `normal` in the mixin always won and no brand could add
 *    tracking to body copy. Emitting every preset's tracking costs 20 `:root`
 *    declarations and buys a fully brand-restatable axis, and the mixins carry
 *    no hardcoded fallback at all. `normal` rather than `0` on purpose: `0`
 *    forbids the UA's justification adjustment, `normal` permits it, and
 *    "no tracking authored" means the latter.
 */
function formatLetterSpacingValue(raw) {
  if (raw === undefined || raw === null) return null;
  const str = String(raw).trim();
  const pct = /^(-?[\d.]+)%$/.exec(str);
  const value = pct ? `${parseFloat(pct[1]) / 100}em` : str;
  if (!Number.isNaN(parseFloat(value)) && parseFloat(value) === 0) return 'normal';
  return value;
}

/**
 * The other half — and the reason it always returns `null` today.
 *
 * `textDecoration` is only ever non-`none` on the `-underline` presets, and
 * every emitter below filters `-underline` (and `-italic`) out of the output
 * set entirely. So on the tokens that ARE emitted the authored value is
 * uniformly `{text-decoration.none}`, and emitting it would add 40 `:root`
 * declarations of the CSS initial value with no call site able to observe a
 * difference.
 *
 * The honest fix for text-decoration is therefore NOT here: it is to stop
 * filtering the `-underline` presets out of emission, which is a change to the
 * public token surface (10 new tier-1 + 10 new tier-2 names) and a design
 * decision, not a formatter bug. Recorded here rather than left implicit so
 * the next reader does not re-derive it.
 */
function formatTextDecorationValue(raw) {
  if (raw === undefined || raw === null) return null;
  const str = String(raw).trim();
  return str === 'none' ? null : str;
}

/**
 * The `[name, value]` pairs a single token contributes: itself, plus any
 * companion custom properties carrying composite sub-values that the primary
 * value's CSS shorthand cannot express.
 *
 * Emitted for every typography preset in BOTH tiers, and for the same reason
 * the primary is: the tier-2
 * mixins in `styles/core/mixins/typography.scss` read the tier-2 custom
 * property, so a tier-2 preset without its companion would silently lose the
 * tracking the tier-1 preset it aliases carries.
 *
 * `referenceName` mirrors the `outputReferences` treatment of the primary
 * value. When it is supplied (a tier-2 token whose value is a whole-string
 * alias) the companion is emitted as `var(--al-<tier-1>-letter-spacing)`
 * rather than a copy of the resolved literal, so the alias chain stays intact
 * and a brand restating the tier-1 preset moves the tier-2 tracking with it.
 */
function companionsFor(token, primaryName, referenceName) {
  const isPreset = token.name.startsWith('typography-preset-');
  const isThemePreset = token.name.startsWith('theme-typography-');
  if (!isPreset && !isThemePreset) return [];
  const value = tokenValue(token);
  if (!value || typeof value !== 'object') return [];
  const pairs = [];
  const asRef = (suffix) => `var(--${themePrefix}-${referenceName}${suffix})`;
  const tracking = formatLetterSpacingValue(value.letterSpacing);
  if (tracking !== null) {
    pairs.push([primaryName + '-letter-spacing', referenceName ? asRef('-letter-spacing') : tracking]);
  }
  const decoration = formatTextDecorationValue(value.textDecoration);
  if (decoration !== null) {
    pairs.push([primaryName + '-text-decoration', referenceName ? asRef('-text-decoration') : decoration]);
  }
  return pairs;
}

function formatSpaceValue(value) {
  return `${parseFloat(value) / themeSpaceBaseSize}rem`;
}

/**
 * DTCG `cubicBezier` -> CSS. The tree authors easing curves as the standard
 * 4-number array (`[0.2, 0, 0, 1]`); CSS wants `cubic-bezier(0.2,0,0,1)`.
 * Comma-joined with no spaces because that is exactly what the CSS strings
 * these tokens were authored as before the conversion read, so the emission is
 * byte-identical. The keyword curves (`ease`, `linear`) stay strings of `$type`
 * `other` — an array would emit `cubic-bezier(...)` where `ease` is emitted
 * today. The SD `cubicBezier/css` transform is deliberately NOT used: it only
 * fires inside the transform groups, which are trimmed (see below), and its
 * spacing differs.
 */
function formatCubicBezierValue(value) {
  return Array.isArray(value) ? `cubic-bezier(${value.join(',')})` : value;
}

// SD v5 stores DTCG values under `$value` when `usesDtcg: true`. Wrap the
// token access so the rest of the format code can stay structurally close
// to the v3 implementation.
function tokenValue(token) {
  return '$value' in token ? token.$value : token.value;
}
function tokenOriginalValue(token) {
  return '$value' in token.original ? token.original.$value : token.original.value;
}

// ---------- custom transform groups (mirror v3 — no DTCG shorthand transforms) ----------
//
// SD v5's `css`/`scss` groups inject `typography/css/shorthand`,
// `shadow/css/shorthand`, etc. that coerce composite tokens into CSS strings
// BEFORE our format runs. v3 had no such transforms — our custom formatters
// (`formatTypographyValue`, `formatBoxShadowValue`) need the raw value
// objects. Register replacement groups that strip the shorthand transforms.

//
// The list below is only the transforms that actually FIRE against this token
// tree, and that is load-bearing rather than tidiness. `time/seconds`,
// `html/icon`, `size/rem`, `asset/url` and `cubicBezier/css` all select on
// `$type`, and every one of them was inert here because the tree carried
// Legacy `$type` values (`sizing`, `fontSizes`, `boxShadow`, `other`, …)
// that no SD filter recognises. Making those `$type` values DTCG-conformant
// would have silently switched all five on:
//
//   - `size/rem` would begin rewriting every `dimension`. It happens to
//     preserve an explicit unit, so `14px` survives — but that is a detail of
//     SD 5.4's implementation, not a contract, and `formatSpaceValue` already
//     does this conversion by hand for the space scale, so the two would race.
//   - `time/seconds` would rewrite the `duration` scale, whose values are
//     already authored in seconds (`0.1s`).
//   - `cubicBezier/css` expects a 4-number ARRAY; this tree authors easing as
//     CSS strings (`ease`, `cubic-bezier(0.2,0,0,1)`), which it cannot consume.
//
// Dropping them is a no-op TODAY (they match nothing today, by construction)
// and is what made the `$type` conformance pass value-neutral. Verified by
// diffing the full `dist-v5/` emission before and after: byte-identical.
// 2026-10-06: animation.timing IS now DTCG `cubicBezier` (arrays) and the
// tier-2 durations are `duration`. That stays value-neutral only because the
// list below omits `cubicBezier/css` and `time/seconds`; the arrays are turned
// into CSS by `formatCubicBezierValue()` instead. Do not add those transforms
// back without diffing `dist-v5/`.
const V3_SHAPE_TRANSFORMS = ['attribute/cti', 'name/kebab', 'color/css'];

StyleDictionary.registerTransformGroup({ name: 'css-v3-shape', transforms: V3_SHAPE_TRANSFORMS });
StyleDictionary.registerTransformGroup({ name: 'scss-v3-shape', transforms: V3_SHAPE_TRANSFORMS });

// ---------- custom formats (ported from v3 to v5 API) ----------

/**
 * The one place a declaration list becomes a CSS rule.
 *
 * `selector` and `layer` are FILE OPTIONS, not literals (R1 of
 * `2026-07-28-scoped-token-emission-brand-wiring`). The defaults —
 * `':root'` and no layer — reproduce the pre-existing output byte for byte,
 * which is the entire back-compat strategy: ten apps, two Storybook previews
 * and ten SCSS files consume the flat `:root` artifacts and none of them had
 * to change.
 */
function renderRule(pairs, { selector = ':root', layer = null } = {}) {
  const indent = layer ? '    ' : '  ';
  const decls = pairs.map(([name, value]) => `${indent}${name}: ${value};`).join('\n');
  if (!layer) return `${selector} {\n${decls}\n}\n`;
  return `@layer ${layer} {\n  ${selector} {\n${decls}\n  }\n}\n`;
}

StyleDictionary.registerFormat({
  name: 'tokens',
  format: ({ dictionary, options }) => {
    const pairs = dictionary.allTokens
      .filter(
        (token) =>
          !token.name.endsWith('-italic') &&
          !token.name.endsWith('-underline') &&
          !token.name.includes('breakpoint')
      )
      .flatMap((token) => {
        let name;
        let value = tokenValue(token);

        if (token.name.includes('font-weight')) {
          name = token.name;
          value = formatFontWeightValue(tokenValue(token));
        } else if (token.name.includes('typography')) {
          name = token.name.endsWith('-regular') ? token.name.replace('-regular', '') : token.name;
          value = formatTypographyValue(tokenValue(token));
        } else if (token.name.includes('box-shadow')) {
          name = token.name;
          value = formatBoxShadowValue(tokenValue(token));
        } else if (!token.name.includes('base') && token.name.includes('space')) {
          name = token.name;
          value = formatSpaceValue(tokenValue(token));
        } else {
          name = token.name;
          value = formatCubicBezierValue(tokenValue(token));
        }

        // Captured so the composite companions below can be emitted as
        // references too, instead of copies of the resolved literal.
        let referenceName = null;
        if (token.name.includes('theme') && options.outputReferences) {
          const origValue = tokenOriginalValue(token);
          if (usesReferences(origValue)) {
            const refs = getReferences(origValue, dictionary.tokens, { usesDtcg: true });
            refs.forEach((ref) => {
              const refName = ref.name.endsWith('-regular') ? ref.name.replace('-regular', '') : ref.name;
              referenceName = refName;
              value = `var(--${themePrefix}-${refName})`;
            });
          }
        }
        const primary = `--${themePrefix}-${name}`;
        return [[primary, value], ...companionsFor(token, primary, referenceName)];
      });

    // R2 — scoped (host) emission is a DELTA, not a copy.
    //
    // `options.onlyNames` (a Set of `--al-…` names) and `options.omitEqualTo`
    // (a Map of `--al-…` -> value read back from an already-emitted `:root`
    // artifact) narrow the declaration list to exactly what the host has to
    // restate. Both are absent for every `:root` file, so those keep emitting
    // the full surface unchanged.
    //
    // Deltas rather than full 17 KB copies because a host INHERITS the base
    // `:root` values through the shadow boundary — restating them costs
    // ~105 KB across the matrix (3.2x the CI bundle allowance) to compute the
    // same thing. See the spec's T9 measurement.
    const only = options.onlyNames ?? null;
    const base = options.omitEqualTo ?? null;
    const kept = pairs.filter(
      ([name, value]) =>
        (!only || only.has(name)) && (!base || base.get(name) !== String(value))
    );

    return comment + renderRule(kept, { selector: options.selector, layer: options.layer });
  },
});

StyleDictionary.registerFormat({
  name: 'al-scss-vars',
  format: ({ dictionary, options }) => {
    const breakpointVariables = dictionary.allTokens
      .filter((token) => token.name.includes('breakpoint'))
      .map((token) => {
        let value = JSON.parse(JSON.stringify(tokenValue(token)));
        const origValue = tokenOriginalValue(token);
        if (options.outputReferences && usesReferences(origValue)) {
          const refs = getReferences(origValue, dictionary.tokens, { usesDtcg: true });
          value = refs.map((ref) => `breakpoint-${ref.name}`).join(', ');
        }
        return `$${themePrefix}-${token.name}: ${value};`;
      })
      .join('\n');

    const themeDeclaration = `$${themePrefix}-theme-prefix: '${themePrefix}';\n`;
    return comment + themeDeclaration + breakpointVariables;
  },
});

StyleDictionary.registerFormat({
  name: 'al-json-flat',
  format: ({ dictionary, options }) => {
    const entries = dictionary.allTokens
      .filter((token) => !token.name.endsWith('-italic') && !token.name.endsWith('-underline'))
      .flatMap((token) => {
        let name;
        let value;
        if (token.name.includes('font-weight')) {
          name = token.name;
          value = formatFontWeightValue(tokenValue(token));
        } else if (token.name.includes('typography')) {
          name = token.name.endsWith('-regular') ? token.name.replace('-regular', '') : token.name;
          value = formatTypographyValue(tokenValue(token));
        } else if (token.name.includes('box-shadow')) {
          name = token.name;
          value = formatBoxShadowValue(tokenValue(token));
        } else {
          name = token.name;
          value = formatCubicBezierValue(tokenValue(token));
        }

        // Captured so the composite companions below can be emitted as
        // references too, instead of copies of the resolved literal.
        let referenceName = null;
        if (token.name.includes('theme') && options.outputReferences) {
          const origValue = tokenOriginalValue(token);
          if (usesReferences(origValue)) {
            const refs = getReferences(origValue, dictionary.tokens, { usesDtcg: true });
            refs.forEach((ref) => {
              const refName = ref.name.endsWith('-regular') ? ref.name.replace('-regular', '') : ref.name;
              referenceName = refName;
              value = `var(--${themePrefix}-${refName})`;
            });
          }
        }
        // companionsFor returns `--al-…` CSS custom-property names; this
        // format keys on the bare `al-…` name, so strip the leading `--`.
        return [
          [`${themePrefix}-${name}`, value],
          ...companionsFor(token, `--${themePrefix}-${name}`, referenceName).map(([n, v]) => [n.slice(2), v]),
        ];
      });

    const variables = entries
      .map(([name, value], index) => `  "${name}": "${value}"${index === entries.length - 1 ? '' : ','}`)
      .join('\n');

    return `{\n${variables}\n}`;
  },
});

// ---------- per-theme / per-brand config ----------

const themeSources = (themeName) => [
  `${SD_ROOT}/tokens-dtcg/tier-1/*.json`,
  `${SD_ROOT}/tokens-dtcg/tier-2/*.json`,
  `${SD_ROOT}/tokens-dtcg/tier-2/theme/${themeName}/*.json`,
  `${SD_ROOT}/tokens-dtcg/tier-3/theme/${themeName}/*.json`,
];

const themeConfig = (themeName, { withCore = false } = {}) => {
  const scssFiles = [
    {
      destination: `tokens-${themeName}.scss`,
      format: 'tokens',
      options: { outputReferences: true },
    },
  ];
  if (withCore) {
    // Mirror v3: variables.scss is emitted from each theme build,
    // overwriting (output is theme-independent — only breakpoints —
    // so the overwrite is idempotent).
    scssFiles.push({
      destination: '../../core/variables.scss',
      format: 'al-scss-vars',
      options: { outputReferences: true },
    });
  }
  const platforms = {
    css: {
      transformGroup: 'css-v3-shape',
      buildPath: 'dist-v5/css/theme/',
      files: [
        {
          destination: `tokens-${themeName}.css`,
          format: 'tokens',
          options: { outputReferences: true },
        },
      ],
    },
    scss: {
      transformGroup: 'scss-v3-shape',
      buildPath: 'dist-v5/scss/theme/',
      files: scssFiles,
    },
  };
  if (withCore) {
    platforms.json = {
      transformGroup: 'scss-v3-shape',
      buildPath: 'dist-v5/',
      files: [
        {
          destination: 'tokens.json',
          format: 'al-json-flat',
          options: { outputReferences: true },
        },
      ],
    };
  }
  return {
    usesDtcg: true,
    log: { verbosity: 'silent', warnings: 'disabled' },
    source: themeSources(themeName),
    platforms,
  };
};

const brandIncludes = (themeName) => [
    `${SD_ROOT}/tokens-dtcg/tier-1/*.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/animations.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/borders.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/icons.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/layout.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/opacity.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/shadows.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/spacing.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/typography.json`,
    `${SD_ROOT}/tokens-dtcg/tier-2/theme/${themeName}/*.json`,
    `${SD_ROOT}/tokens-dtcg/tier-3/theme/${themeName}/*.json`,
];

// Brand deltas only — the full token surface comes from `brandIncludes` above.
//
// A `tokens-dtcg/tier-3/brand/${brandName}/*.json` glob used to sit here and
// matched nothing: `styles/tokens-dtcg/tier-3/` has never had a `brand/`
// directory.
// Removed rather than materialized so a tier-3 brand layer is re-added
// deliberately — if brand identities need one, add the authored files under
// `styles/tokens-dtcg/tier-3/brand/<brand>/` AND restore the glob here together.
//
// PER-MODE BRAND COLOR DELTAS (spec 2026-08-20-southleft-example-app, T9
// round 2 — see `.altitude/BRANDS.md` §1/§6 update). A brand's `colors.json`
// is theme-INDEPENDENT by construction — the same file builds against both
// `light` and `dark` includes (see `brands` array below), so a literal value
// written there resolves identically in both builds and gets classified
// `invariant` by the delta-splitter two screens down. That's correct for an
// accent hue (southleft's red is red in both modes) but wrong for a NEUTRAL
// canvas that must itself flip warm-dark ↔ warm-light with the mode — no
// single theme-independent value can do that.
// `tier-2/brand/<brand>/mode/<theme>/colors.json` (note: nested one level so
// the existing `tier-2/brand/<brand>/*.json` glob — intentionally
// non-recursive, matching `brandIncludes`'s own `tier-2/theme/${themeName}/
// *.json` pattern — never touches it) is loaded ADDITIONALLY, only for that
// theme's build. Because the two theme builds now genuinely diverge on these
// properties, the existing delta-splitter (unchanged) correctly classifies
// them `perMode` and routes them into the `:host([brand='<brand>']
// [mode='<theme>'])` block (0,3,0) — which already outranks the mode axis's
// own `:host([mode])` block (0,2,0) restating `background.default` /
// `content.default` (BRANDS.md §5's "mode owns these" note predates any
// brand having a reason to override them; the 0,3,0 selector was always
// there for exactly this case). No other brand file, the delta-splitter, or
// the `theme.scss` `@use` order needed to change.
const brandSources = (brandName, themeName) => {
  const files = [`${SD_ROOT}/tokens-dtcg/tier-2/brand/${brandName}/*.json`];
  if (themeName) {
    const modeFile = `${SD_ROOT}/tokens-dtcg/tier-2/brand/${brandName}/mode/${themeName}/colors.json`;
    if (existsSync(modeFile)) files.push(modeFile);
  }
  return files;
};

const brandConfig = (themeName, brandName) => ({
  usesDtcg: true,
  log: { verbosity: 'verbose' },
  include: brandIncludes(themeName),
  source: brandSources(brandName, themeName),
  platforms: {
    css: {
      transformGroup: 'css-v3-shape',
      buildPath: `dist-v5/css/brand/`,
      files: [
        {
          destination: `tokens-${brandName}-${themeName}.css`,
          format: 'tokens',
          options: { outputReferences: true },
        },
      ],
    },
    scss: {
      transformGroup: 'scss-v3-shape',
      buildPath: `dist-v5/scss/brand/`,
      files: [
        {
          destination: `tokens-${brandName}-${themeName}.scss`,
          format: 'tokens',
          options: { outputReferences: true },
        },
      ],
    },
  },
});

// ---------- scoped `:host` emission (R2) ----------
//
// WHY THIS EXISTS. `<al-theme brand mode density contrast>` has always typed a
// `brand` attribute and `components/theme/theme.scss` has never had a rule
// that reads it, so `brand` was inert while CLAUDE.md, MIGRATION.md and
// `.changeset/v2-major.md` all advertised working multi-brand pages. These
// partials are the missing half.
//
// WHY DELTAS. `:host` blocks are compiled into `<al-theme>`'s `static styles`,
// so their bytes ship in the JS bundle. Restating each brand x mode bundle in
// full costs 104,962 B across the matrix — 3.2x the 33,309 B that CI's
// `baselines-bundle` job allows (`.github/workflows/v2-checks.yml:191-220`).
// A host INHERITS every `--al-*` it does not restate, so the delta computes
// the identical value for ~15 KB. Cost of the choice, stated plainly:
// `<al-theme>` COMPOSES ON TOP of a base token sheet, it does not replace one.
// A page with no `:root` bundle loaded gets brand deltas resolving against
// nothing.
//
// WHY THE BRAND BLOCKS ARE SPLIT IN TWO. `<al-theme>` does not reflect its
// properties, so `<al-theme brand="southleft">` with no `mode` attribute matches
// no `[mode]` selector. Splitting each brand delta into
//   * `:host([brand='x'])`          — the part that is identical in every mode
//                                     the brand builds AND is not a property
//                                     the base theme varies by mode, and
//   * `:host([brand='x'][mode='y'])` — the remainder
// means a brand always contributes its mode-independent identity (type ramp,
// radii, spacing, border weights) even with no `mode` set, and never asserts a
// colour that contradicts the mode actually in force. Measured: southleft
// needs no per-mode block at all today.
//
// SPECIFICITY. `:host([brand][mode])` is exactly 0,3,0 and `:host([brand])` /
// `:host([mode])` are 0,2,0 — the budget `scripts/check-css-layers.js` enforces
// is 0,3,0, so the brand x mode form sits on the ceiling with zero headroom. A
// third attribute is not available; that is why the other four axes are
// emitted as their own single-attribute rules (see "<al-theme> axes" below)
// rather than combined with brand/mode. The checker lints these generated files directly
// (it used to only read `components/<name>/<name>.scss`, which `@use` hides).

const HOST_DIR = 'dist-v5/scss/host';

/** Parse `--name: value;` out of an emitted artifact. */
async function readDeclarations(file) {
  const text = await fs.readFile(file, 'utf8');
  const map = new Map();
  for (const line of text.split('\n')) {
    const m = line.match(/^\s*(--[A-Za-z0-9-]+):\s*(.*);\s*$/);
    if (m) map.set(m[1], m[2]);
  }
  return map;
}

function hostPlatform(destination, selector, { onlyNames = null, omitEqualTo = null }) {
  return {
    scss: {
      transformGroup: 'scss-v3-shape',
      buildPath: `${HOST_DIR}/`,
      files: [
        {
          destination,
          format: 'tokens',
          options: { outputReferences: true, selector, layer: 'al.theme', onlyNames, omitEqualTo },
        },
      ],
    },
  };
}

// ---------- <al-theme> axes: density / contrast / motion / shape ----------
//
// `brand` and `mode` are token bundles; these four axes used to be literal
// declarations hand-written in `components/theme/theme.scss`. Each is now a
// set of DTCG MODE FILES — `tokens-dtcg/tier-2/axis/<axis>/<mode>.json`, one
// file per attribute value, every file of an axis naming the same token paths
// — and this section turns them into the `:host([…])` rules theme.scss loads.
// The tree is the importer contract too: a canvas tool reads one collection per
// axis directory and one mode per file (`.altitude/AXES.md` §2).
//
// The mode files are NOT in any `:root` build — `tier-2/*.json` is a
// non-recursive glob — because an axis is a scoped override, and because two
// of them (motion, shape) carry role tokens that must never get a `:root`
// default (`.altitude/AXES.md` §2.3).
//
// WHAT A MODE FILE CANNOT SAY, AND THIS TABLE DOES: which attribute selector a
// mode is written under, and in what order. The order is load-bearing — the
// motion rules rely on source order at equal specificity (`full` must follow
// the reduce media query so it can opt back out of it) — so it is stated here
// once rather than inferred from file names.
//
//   rules[].types  limit a rule to tokens of these `$type`s. The OS
//                  reduced-motion rule reuses `reduced`'s durations and nothing
//                  else, exactly as the hand-written block did.
//   (no rule)      a DEFAULT mode with no rule emits nothing: `comfortable`
//                  density and `default` shape are the base bundle / the
//                  component fallbacks, so asserting them would change nesting
//                  behaviour. `normal` contrast and `full` motion DO have rules
//                  because the hand-written CSS did — a nested theme resets to
//                  them rather than inheriting its ancestor's choice.
//
// Per-token `$extensions["org.altitude.axis"].css` overrides `$value` in the
// emitted CSS:
//   "initial"  emit the guaranteed-invalid value, so a component's
//              `var(--role, var(--legacy))` fallback resolves. `$value` records
//              what that fallback resolves to, for importers.
//   "omit"     emit nothing (the property inherits / falls back). Used for the
//              default shape mode, pill's untouched `indicator`, and the motion
//              `transition` composites, which are design-tool data only.
const AXIS_DIR = `${SD_ROOT}/tokens-dtcg/tier-2/axis`;
/** Under the host dir so the legacy mirror skips it, like the brand/mode partials. */
const AXIS_HOST_DIR = 'dist-v5/scss/host/axis';
const AXES = [
  {
    axis: 'density',
    modes: ['compact', 'cozy', 'comfortable'],
    rules: [
      { mode: 'compact', selector: ":host([density='compact'])" },
      { mode: 'cozy', selector: ":host([density='cozy'])" },
    ],
  },
  {
    axis: 'contrast',
    modes: ['normal', 'more'],
    rules: [
      { mode: 'more', selector: ":host([contrast='more'])" },
      // Not `[contrast='normal']`: <al-theme> never reflects its default, so
      // that selector would miss every theme that left the attribute unset.
      { mode: 'normal', selector: ":host(:not([contrast='more']))" },
    ],
  },
  {
    axis: 'motion',
    modes: ['full', 'reduced', 'expressive'],
    rules: [
      { mode: 'reduced', selector: ":host([motion='reduced'])" },
      { mode: 'expressive', selector: ":host([motion='expressive'])" },
      // Accessibility-first: the OS preference beats everything but an
      // explicit `full`, including `expressive` above (same specificity, later).
      {
        mode: 'reduced',
        selector: ":host(:not([motion='full']))",
        media: '(prefers-reduced-motion: reduce)',
        types: ['duration'],
      },
      // Must come after the media rule: both are 0,2,0, so order lets `full` win.
      { mode: 'full', selector: ":host([motion='full'])" },
    ],
  },
  {
    axis: 'shape',
    modes: ['default', 'sharp', 'pill'],
    rules: [
      { mode: 'sharp', selector: ":host([shape='sharp'])" },
      { mode: 'pill', selector: ":host([shape='pill'])" },
    ],
  },
];

/** Dot-paths of every token leaf in a DTCG document, in authored order. */
function leafPaths(node, segs = [], out = []) {
  if (!node || typeof node !== 'object' || Array.isArray(node)) return out;
  if ('$value' in node) {
    out.push(segs.join('.'));
    return out;
  }
  for (const [k, v] of Object.entries(node)) {
    if (!k.startsWith('$')) leafPaths(v, [...segs, k], out);
  }
  return out;
}

/** A resolved token value as one CSS string (composites included). */
function cssLiteral(value) {
  if (Array.isArray(value)) return formatCubicBezierValue(value);
  if (value && typeof value === 'object') {
    // DTCG transition: duration, timingFunction, delay.
    if ('duration' in value || 'timingFunction' in value) {
      return [value.duration, formatCubicBezierValue(value.timingFunction), value.delay].filter(Boolean).join(' ');
    }
    return JSON.stringify(value);
  }
  return String(value);
}

/**
 * Emit the axis partials and the `axes.json` manifest. Returns the partial
 * file names, in the order theme.scss loads them.
 */
async function buildAxes({ baseSources }) {
  const manifest = {
    $comment:
      'Generated by styles/tokens-config.v5.mjs from styles/tokens-dtcg/tier-2/axis/<axis>/<mode>.json. ' +
      'One entry per <al-theme> attribute: its modes, the resolved value of every token in every mode, ' +
      'and the exact host rules emitted for it. See .altitude/AXES.md.',
    axes: {},
  };

  // The base `:root` build, to prove each DEFAULT mode says what :root says.
  const baseSd = new StyleDictionary({
    usesDtcg: true,
    log: { verbosity: 'silent', warnings: 'disabled' },
    source: baseSources,
    platforms: { axis: { transformGroup: 'css-v3-shape' } },
  });
  const base = await baseSd.getPlatformTokens('axis');
  const baseValue = new Map(base.allTokens.map((t) => [t.path.join('.'), t.$value]));

  const partials = [];
  for (const spec of AXES) {
    const dir = path.join(AXIS_DIR, spec.axis);
    const onDisk = (await fs.readdir(dir)).filter((f) => f.endsWith('.json')).map((f) => f.slice(0, -5));
    const missing = spec.modes.filter((m) => !onDisk.includes(m));
    const unknown = onDisk.filter((m) => !spec.modes.includes(m));
    if (missing.length || unknown.length) {
      throw new Error(
        `[tokens:v5] axis "${spec.axis}": mode files and the AXES table disagree ` +
          `(missing: ${missing.join(', ') || 'none'}; not in table: ${unknown.join(', ') || 'none'})`
      );
    }

    const modes = {};
    let defaultMode = null;
    const tokenOrder = []; // union of every mode's paths: a mode may be sparse
    for (const mode of spec.modes) {
      const file = path.join(dir, `${mode}.json`);
      const doc = JSON.parse(await fs.readFile(file, 'utf8'));
      const meta = doc.$extensions?.['org.altitude.axis'] ?? {};
      if (meta.axis !== spec.axis || meta.mode !== mode) {
        throw new Error(`[tokens:v5] ${spec.axis}/${mode}.json: $extensions["org.altitude.axis"] must name axis "${spec.axis}" and mode "${mode}"`);
      }
      if (meta.default === true) {
        if (defaultMode) throw new Error(`[tokens:v5] axis "${spec.axis}" declares two default modes (${defaultMode}, ${mode})`);
        defaultMode = mode;
      }
      const order = leafPaths(doc);
      for (const p of order) if (!tokenOrder.includes(p)) tokenOrder.push(p);

      const sd = new StyleDictionary({
        usesDtcg: true,
        log: { verbosity: 'silent', warnings: 'disabled' },
        include: baseSources,
        source: [file],
        platforms: { axis: { transformGroup: 'css-v3-shape' } },
      });
      const dict = await sd.getPlatformTokens('axis');
      const own = dict.allTokens
        .filter((t) => path.resolve(t.filePath) === path.resolve(file))
        .sort((a, b) => order.indexOf(a.path.join('.')) - order.indexOf(b.path.join('.')));

      const tokens = own.map((t) => {
        const css = t.$extensions?.['org.altitude.axis']?.css ?? null;
        if (css !== null && css !== 'initial' && css !== 'omit') {
          throw new Error(`[tokens:v5] ${spec.axis}/${mode}.json#${t.path.join('.')}: unknown org.altitude.axis.css "${css}"`);
        }
        const original = tokenOriginalValue(t);
        let declared = null;
        if (css === 'initial') declared = 'initial';
        else if (css === null) {
          if (typeof original === 'string' && usesReferences(original)) {
            if (!/^\{[^{}]+\}$/.test(original)) {
              throw new Error(`[tokens:v5] ${spec.axis}/${mode}.json#${t.path.join('.')}: an axis value is a literal or ONE whole alias`);
            }
            const [ref] = getReferences(original, dict.tokens, { usesDtcg: true });
            declared = `var(--${themePrefix}-${ref.name})`;
          } else if (original && typeof original === 'object' && !Array.isArray(original)) {
            throw new Error(`[tokens:v5] ${spec.axis}/${mode}.json#${t.path.join('.')}: composite values must be css:"omit"`);
          } else {
            // The AUTHORED literal, not the transformed one: `currentColor` is
            // a CSS keyword `color/css` would otherwise rewrite.
            declared = cssLiteral(original);
          }
        }
        return {
          path: t.path.join('.'),
          name: `--${themePrefix}-${t.name}`,
          type: t.$type,
          css,
          declared,
          value: t.$value && typeof t.$value === 'object' && !Array.isArray(t.$value)
            ? Object.fromEntries(Object.entries(t.$value).map(([k, v]) => [k, cssLiteral(v)]))
            : cssLiteral(t.$value),
        };
      });
      modes[mode] = { file: path.relative(SD_ROOT, file).split(path.sep).join('/'), tokens };
    }
    if (!defaultMode) throw new Error(`[tokens:v5] axis "${spec.axis}" has no default mode`);

    // A default mode with a plain value must agree with :root, or the axis
    // would describe a default the page does not render. This replaces the
    // "these values MUST track tier-2" comments theme.scss used to carry.
    for (const tok of modes[defaultMode].tokens) {
      if (tok.css !== null || !baseValue.has(tok.path)) continue;
      const expected = cssLiteral(baseValue.get(tok.path));
      if (tok.value !== expected) {
        throw new Error(
          `[tokens:v5] axis "${spec.axis}": default mode "${defaultMode}" says ${tok.path} = ${tok.value}, ` +
            `but the :root build says ${expected}. Change both together.`
        );
      }
    }

    // Every non-default mode must be reachable, or its file is inert.
    for (const mode of spec.modes) {
      if (mode !== defaultMode && !spec.rules.some((r) => r.mode === mode)) {
        throw new Error(`[tokens:v5] axis "${spec.axis}": mode "${mode}" has no rule in AXES, so it would never apply`);
      }
    }

    const rules = spec.rules.map((rule) => {
      const decls = modes[rule.mode].tokens.filter(
        (t) => t.declared !== null && (!rule.types || rule.types.includes(t.type))
      );
      return {
        mode: rule.mode,
        selector: rule.selector,
        media: rule.media ?? null,
        declarations: Object.fromEntries(decls.map((t) => [t.name, t.declared])),
      };
    });

    // UNLAYERED on purpose. theme.scss loads these with `meta.load-css()`
    // INSIDE its own `@layer al.theme { … }` block, so the compiled component
    // CSS is byte-identical to the hand-written rules this replaced (one layer
    // block, same rules, same order). Wrapping each file in its own
    // `@layer al.theme` would be semantically equal but would repeat the
    // wrapper four times. `check-css-layers.js` lints these files separately
    // and asserts they stay unlayered and are loaded inside theme.scss's layer.
    const body = rules
      .map((r) => {
        const pad = r.media ? '    ' : '  ';
        const decls = Object.entries(r.declarations).map(([n, v]) => `${pad}${n}: ${v};`).join('\n');
        const block = `${r.media ? '  ' : ''}${r.selector} {\n${decls}\n${r.media ? '  ' : ''}}`;
        return r.media ? `@media ${r.media} {\n${block}\n}` : block;
      })
      .join('\n');
    const destination = `${spec.axis}.scss`;
    await fs.writeFile(
      `${AXIS_HOST_DIR}/${destination}`,
      `${comment}// <al-theme ${spec.axis}> — from tokens-dtcg/tier-2/axis/${spec.axis}/*.json.\n` +
        `// Loaded by components/theme/theme.scss INSIDE its \`@layer al.theme\` block.\n` +
        `${body}\n`
    );
    partials.push(destination);

    // Manifest: tokens keyed by CSS name, value per mode — the shape an
    // importer building one variable collection per axis wants.
    const byName = {};
    for (const p of tokenOrder) {
      const sample = spec.modes.map((m) => modes[m].tokens.find((t) => t.path === p)).find(Boolean);
      if (!sample) continue;
      byName[sample.name] = {
        path: p,
        type: sample.type,
        // false for design-tool-only tokens (the motion `transition`
        // composites): no rule ever declares the custom property.
        emitted: rules.some((r) => sample.name in r.declarations),
        values: Object.fromEntries(
          // null = the mode does not name the token, so the base value applies.
          spec.modes.map((m) => [m, modes[m].tokens.find((t) => t.path === p)?.value ?? null])
        ),
      };
    }
    manifest.axes[spec.axis] = {
      attribute: spec.axis,
      default: defaultMode,
      modes: spec.modes,
      source: `tokens-dtcg/tier-2/axis/${spec.axis}/`,
      tokens: byName,
      rules,
    };
  }

  await checkMotionUses();
  await fs.writeFile('dist-v5/axes.json', JSON.stringify(manifest, null, 2) + '\n');
  return partials;
}

/**
 * The motion USE CASES live in two places by necessity: as DTCG `transition`
 * composites (`theme.animation.transition.<use>` in every motion mode file),
 * which is what a design tool imports, and as the `$al-motion-uses` map in
 * `styles/core/mixins/motion.scss`, which is what components compile against
 * (a composite custom property would freeze its var() references — see that
 * file's header). Fail the build if they disagree, so neither can drift.
 */
async function checkMotionUses() {
  const pairs = (doc, where) => {
    const uses = doc.theme?.animation?.transition ?? {};
    return Object.fromEntries(
      Object.entries(uses).map(([use, tok]) => {
        const d = /^\{theme\.animation\.duration\.role\.(\w+)\}$/.exec(tok.$value?.duration ?? '');
        const e = /^\{theme\.animation\.timing\.role\.(\w+)\}$/.exec(tok.$value?.timingFunction ?? '');
        if (!d || !e) {
          throw new Error(`[tokens:v5] ${where}#theme.animation.transition.${use}: must alias a duration role and an easing role`);
        }
        return [use, `${d[1]},${e[1]}`];
      })
    );
  };
  const spec = AXES.find((a) => a.axis === 'motion');
  let reference = null;
  for (const mode of spec.modes) {
    const where = `tier-2/axis/motion/${mode}.json`;
    const got = pairs(JSON.parse(await fs.readFile(path.join(AXIS_DIR, 'motion', `${mode}.json`), 'utf8')), where);
    if (reference && JSON.stringify(got) !== JSON.stringify(reference)) {
      throw new Error(`[tokens:v5] ${where}: motion use cases differ from ${spec.modes[0]}.json — every mode must pair them the same way`);
    }
    reference ??= got;
  }
  const scss = await fs.readFile(path.join(SD_ROOT, 'core', 'mixins', 'motion.scss'), 'utf8');
  const map = /\$al-motion-uses:\s*\(([\s\S]*?)\n\);/.exec(scss);
  if (!map) throw new Error('[tokens:v5] styles/core/mixins/motion.scss: $al-motion-uses map not found');
  const mixin = Object.fromEntries(
    [...map[1].matchAll(/([\w-]+):\s*\((\w+),\s*(\w+)\)/g)].map((m) => [m[1], `${m[2]},${m[3]}`])
  );
  if (JSON.stringify(mixin) !== JSON.stringify(reference)) {
    throw new Error(
      `[tokens:v5] motion use cases disagree: tokens say ${JSON.stringify(reference)}, ` +
        `styles/core/mixins/motion.scss $al-motion-uses says ${JSON.stringify(mixin)}. Change both together.`
    );
  }
}

// ---------- main ----------

async function build() {
  // Run from the workspace root so `buildPath: 'dist-v5/...'` lands under
  // libs/al-web-components/styles/dist-v5/.
  process.chdir(SD_ROOT);

  // Clean previous v5 output so deletions surface.
  await fs.rm('dist-v5', { recursive: true, force: true });

  const themes = ['light', 'dark'];
  // Which mode `:root` carries in a project bundle. Dark, matching what
  // main.css has baked into `:root` since v3 — changing it would silently
  // repaint every consumer that loads a bundle and sets no mode.
  const DEFAULT_MODE = 'dark';
  const projectBundles = [];
  const brands = [
    // `altitude` is the default brand (`<al-theme brand>` in components/theme/theme.ts).
    // It builds in BOTH modes because the base theme output it used to stand in for
    // exists in both. southleft used to be dark-only ("ink"); spec
    // 2026-08-20-southleft-example-app adds its light "paper" mode — the brand
    // token deltas (colour, radius, border-width, shadow, typography) are
    // theme-independent, so the SAME `tier-2/brand/southleft/*.json` files now
    // build against both base themes.
    { theme: 'light', brand: 'altitude' },
    { theme: 'dark', brand: 'altitude' },
    { theme: 'dark', brand: 'southleft' },
    { theme: 'light', brand: 'southleft' },
  ];

  // Per-theme css + scss tokens files. v3 emits variables.scss + tokens.json
  // from each theme build to the same path, so the *last* build wins. v3
  // order is light → dark, so dark is the surviving copy on disk. Match that.
  for (const theme of themes) {
    const sd = new StyleDictionary(themeConfig(theme, { withCore: theme === 'dark' }));
    await sd.buildAllPlatforms();
  }

  // Per-brand css + scss tokens files.
  for (const { theme, brand } of brands) {
    const sd = new StyleDictionary(brandConfig(theme, brand));
    await sd.buildAllPlatforms();
  }

  // ---- scoped `:host` partials for <al-theme> (R2) ----
  //
  // Derived from the artifacts the two loops above just wrote, so a host block
  // can never disagree with the `:root` block it is a delta of. Emitted last
  // for that reason.

  const themeDecls = Object.fromEntries(
    await Promise.all(
      themes.map(async (t) => [t, await readDeclarations(`dist-v5/css/theme/tokens-${t}.css`)])
    )
  );

  // Properties the BASE theme varies by mode (23 today: the default
  // background/content/border surface, the shadow tint, and the six
  // `--al-box-shadow-N` literals that recompute from it). A brand override of
  // one of these has to live in a `[mode]`-qualified block or it would assert
  // a dark value on a light host.
  const modeVarying = new Set();
  for (const t of themes) {
    for (const [name, value] of themeDecls[t]) {
      if (themes.some((o) => themeDecls[o].get(name) !== value)) modeVarying.add(name);
    }
  }

  const emitted = [];
  async function emitHost(destination, selector, narrowing, theme, brand) {
    const cfg = brand
      ? { include: brandIncludes(theme), source: brandSources(brand, theme) }
      : { source: themeSources(theme) };
    const sd = new StyleDictionary({
      usesDtcg: true,
      log: { verbosity: 'silent', warnings: 'disabled' },
      ...cfg,
      platforms: hostPlatform(destination, selector, narrowing),
    });
    await sd.buildAllPlatforms();
    emitted.push(destination);
  }

  // 1. Mode. Symmetric deltas: each block restates exactly the properties that
  //    differ between the two base themes, so `<al-theme mode="light">` lands
  //    on light values whichever base sheet the page loaded, and
  //    `<al-theme mode="dark">` on a dark page is a no-op restatement.
  //    This replaces the two hardcoded hexes theme.scss used to carry (R4) —
  //    those disagreed with the generated tokens and, sitting on the element,
  //    beat them.
  for (const theme of themes) {
    const other = themes.find((t) => t !== theme);
    await emitHost(
      `tokens-mode-${theme}.scss`,
      `:host([mode='${theme}'])`,
      { omitEqualTo: themeDecls[other] },
      theme,
      null
    );
  }

  // 2. Brand. Split per the header comment. `altitude` is the neutral
  //    reference (`.altitude/BRANDS.md` §6 rule 8) and its bundles are
  //    byte-identical to the base theme, so its delta is empty and no file is
  //    written — an empty rule would be dead weight, and its absence is the
  //    assertion that altitude really is neutral.
  const byBrand = new Map();
  for (const { theme, brand } of brands) {
    if (!byBrand.has(brand)) byBrand.set(brand, []);
    byBrand.get(brand).push(theme);
  }

  /**
   * Every property ANY non-default brand overrides, and in which modes. The
   * default brand needs this to write a RESET block — see the emit below.
   */
  const DEFAULT_BRAND = 'altitude';
  const overriddenByOthers = new Map(); // name -> Set(theme)

  for (const [brand, brandModes] of byBrand) {
    const deltas = new Map();
    for (const theme of brandModes) {
      const bundle = await readDeclarations(`dist-v5/css/brand/tokens-${brand}-${theme}.css`);
      const d = new Map();
      for (const [name, value] of bundle) {
        if (themeDecls[theme].get(name) !== value) d.set(name, value);
      }
      deltas.set(theme, d);
    }
    const allNames = new Set([...deltas.values()].flatMap((d) => [...d.keys()]));
    if (brand !== DEFAULT_BRAND) {
      for (const theme of brandModes) {
        for (const name of deltas.get(theme).keys()) {
          if (!overriddenByOthers.has(name)) overriddenByOthers.set(name, new Set());
          overriddenByOthers.get(name).add(theme);
        }
      }
    }
    const invariant = new Set();
    const perMode = new Set();
    for (const name of allNames) {
      const first = deltas.get(brandModes[0]).get(name);
      const sameInEveryMode = brandModes.every((t) => deltas.get(t).get(name) === first);
      if (sameInEveryMode && !modeVarying.has(name)) invariant.add(name);
      else perMode.add(name);
    }

    if (invariant.size > 0) {
      await emitHost(
        `tokens-brand-${brand}.scss`,
        `:host([brand='${brand}'])`,
        { onlyNames: invariant, omitEqualTo: themeDecls[brandModes[0]] },
        brandModes[0],
        brand
      );
    }
    for (const theme of brandModes) {
      const names = new Set([...perMode].filter((n) => deltas.get(theme).has(n)));
      if (names.size === 0) continue;
      await emitHost(
        `tokens-brand-${brand}-${theme}.scss`,
        `:host([brand='${brand}'][mode='${theme}'])`,
        { onlyNames: names, omitEqualTo: themeDecls[theme] },
        theme,
        brand
      );
    }
  }

  // 2b. THE DEFAULT BRAND'S RESET BLOCK.
  //
  //     `altitude` is the neutral reference, so its delta against the base is
  //     empty and for a long time no file was written for it. That was a real
  //     hole, not an elegance: custom properties INHERIT, so
  //     `<al-theme brand="altitude">` nested inside `<al-theme brand="southleft">`
  //     had nothing to re-declare and simply inherited southleft's values.
  //
  //     It looked fixed on 2026-08-31, but only by accident — the v2 restyle
  //     had moved `background.primary-default` into the MODE partials, which
  //     every host re-declares regardless of brand, so the one property the
  //     probe read happened to reset. `tests`' own note said so plainly: "this
  //     does NOT make empty-delta nesting safe in general: a property that
  //     lives ONLY in a brand partial still inherits through."
  //
  //     2026-09-03 proved it: moving southleft onto the real `color.primary`
  //     and `color.neutral` role ramps put those properties in a brand-only
  //     partial, and the nested-altitude probe went red immediately.
  //
  //     The structural fix is to stop relying on emptiness. For the union of
  //     every property ANY other brand overrides, altitude now restates the
  //     BASE value on its own host. Absence stops being the assertion of
  //     neutrality; an explicit restatement is. It costs one small generated
  //     block and makes nesting work for every property, not the lucky ones.
  if (overriddenByOthers.size > 0) {
    const defaultModes = byBrand.get(DEFAULT_BRAND) ?? themes;
    const resetInvariant = new Set();
    const resetPerMode = new Map(themes.map((t) => [t, new Set()]));
    for (const [name, inThemes] of overriddenByOthers) {
      if (modeVarying.has(name)) {
        for (const t of inThemes) resetPerMode.get(t)?.add(name);
      } else {
        resetInvariant.add(name);
      }
    }

    if (resetInvariant.size > 0) {
      await emitHost(
        `tokens-brand-${DEFAULT_BRAND}.scss`,
        `:host([brand='${DEFAULT_BRAND}'])`,
        { onlyNames: resetInvariant },
        defaultModes[0],
        DEFAULT_BRAND
      );
    }
    for (const theme of themes) {
      const names = resetPerMode.get(theme);
      if (!names || names.size === 0) continue;
      await emitHost(
        `tokens-brand-${DEFAULT_BRAND}-${theme}.scss`,
        `:host([brand='${DEFAULT_BRAND}'][mode='${theme}'])`,
        { onlyNames: names },
        theme,
        DEFAULT_BRAND
      );
    }
  }

  // 3. The entry point `components/theme/theme.scss` @uses. Order matters for
  //    the two 0,2,0 families: mode first, brand second, so that when a brand
  //    and the base theme both name a property the brand wins. (Today they
  //    never collide — `modeVarying` names are routed to the 0,3,0 blocks —
  //    but the ordering makes that a property of the file, not luck.)
  const order = [
    ...emitted.filter((f) => f.startsWith('tokens-mode-')),
    ...emitted.filter((f) => f.startsWith('tokens-brand-') && f.split('-').length === 3),
    ...emitted.filter((f) => f.startsWith('tokens-brand-') && f.split('-').length > 3),
  ];
  await fs.writeFile(
    `${HOST_DIR}/_index.scss`,
    `${comment}// Scoped token blocks for <al-theme>. Generated by styles/tokens-config.v5.mjs.\n` +
      `// Loaded by components/theme/theme.scss; see that file and the emitter's\n` +
      `// "scoped \`:host\` emission" comment for the delta/specificity rationale.\n` +
      order.map((f) => `@use './${f}';`).join('\n') +
      '\n'
  );

  // 3b. The four non-palette axes (density / contrast / motion / shape) —
  //     see "<al-theme> axes" above. Under the host dir so the legacy mirror
  //     skips the partials like the brand/mode ones; `axes.json` IS mirrored,
  //     so it ships in `dist/css/`.
  await fs.mkdir(AXIS_HOST_DIR, { recursive: true });
  const axisPartials = await buildAxes({ baseSources: themeSources(DEFAULT_MODE) });

  // ---- 4. PER-PROJECT BUNDLES ----
  //
  //     One design system, one stylesheet, both modes — which is exactly how
  //     the Figma side models it: a file IS a system, `Tier 1 | Colors` holds
  //     that system's values, and `Tier 2 | Theme` carries Light and Dark as
  //     two modes of ONE collection. There is no brand dimension there, and
  //     after this there is none here either.
  //
  //     Composed from the artifacts the loops above already wrote, never
  //     re-derived, so a project bundle cannot disagree with the `:root` build
  //     it is made of — the same rule the host partials follow.
  //
  //     Shape, and why:
  //       :root, [data-al-project='<id>']
  //                                the DEFAULT mode in full. Dark at :root,
  //                                because that is what main.css has always
  //                                baked into :root and this must not move the
  //                                default rendering.
  //
  //                                The second selector is what keeps TWO design
  //                                systems able to share a document, which the
  //                                brand axis used to provide and which dropping
  //                                it would otherwise have cost. Load both
  //                                bundles and each subtree marked
  //                                `data-al-project` resolves its own system;
  //                                `:root` belongs to whichever loaded last, so
  //                                a two-system page marks both subtrees
  //                                explicitly rather than relying on order.
  //       [data-al-mode='light']   only the properties that differ by mode.
  //       [data-al-mode='dark']    the same delta, re-asserted, so a dark scope
  //                                nested INSIDE a light one resolves back —
  //                                without it, scoping would only work one way.
  //
  //     Attribute selectors rather than a media query or a class: they match at
  //     ANY depth, so a subtree can carry its own mode, and custom properties
  //     inherit through shadow boundaries from whatever element matched. That is
  //     what keeps scoped theming working once the palette leaves <al-theme>.
  const PROJECT_DIR = 'dist-v5/css/project';
  await fs.mkdir(PROJECT_DIR, { recursive: true });
  const projectNames = [...new Set(brands.map((b) => b.brand))];
  for (const project of projectNames) {
    const perMode = Object.fromEntries(
      await Promise.all(
        themes.map(async (t) => [t, await readDeclarations(`dist-v5/css/brand/tokens-${project}-${t}.css`)])
      )
    );
    const base = perMode[DEFAULT_MODE];
    const modeDelta = (t) =>
      [...perMode[t]].filter(([name, value]) =>
        themes.some((other) => perMode[other].get(name) !== value)
      );

    const parts = [
      `/* ${project} — generated by styles/tokens-config.v5.mjs. Do not edit directly.
` +
        `   One design system, both modes. Set data-al-mode on any element to scope a mode. */
`,
      renderRule([...base], { selector: `:root, [data-al-project='${project}']` }),
    ];
    for (const t of themes) {
      const delta = modeDelta(t);
      if (delta.length) parts.push(renderRule(delta, { selector: `[data-al-mode='${t}']` }));
    }
    await fs.writeFile(`${PROJECT_DIR}/${project}.css`, parts.join('\n'));
    projectBundles.push(`${project}.css (${base.size} base + ${modeDelta('light').length} per mode)`);
  }

  console.log(
    `[tokens:v5] build complete → libs/al-web-components/styles/dist-v5/ ` +
      `(${order.length} scoped host partial(s), ${axisPartials.length} axis partial(s), ` +
      `${projectBundles.length} project bundle(s): ${projectBundles.join(', ')})`
  );
}

build().catch((err) => {
  console.error('[tokens:v5] FAIL:', err);
  process.exit(1);
});
