// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { svg } from 'lit';
import type { AltitudeIconDef } from '../types';

/** Phosphor `key-return` (regular). */
const glyph: AltitudeIconDef = { v: '0 0 256 256', c: /*#__PURE__*/ svg`<path d="M184,104v32a8,8,0,0,1-8,8H99.31l10.35,10.34a8,8,0,0,1-11.32,11.32l-24-24a8,8,0,0,1,0-11.32l24-24a8,8,0,0,1,11.32,11.32L99.31,128H168V104a8,8,0,0,1,16,0Zm48-48V200a16,16,0,0,1-16,16H40a16,16,0,0,1-16-16V56A16,16,0,0,1,40,40H216A16,16,0,0,1,232,56ZM216,200V56H40V200H216Z"/>` };

export default glyph;
