// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { svg } from 'lit';
import type { AltitudeIconDef } from '../types';

/** Phosphor `line-vertical` (regular). */
const glyph: AltitudeIconDef = { v: '0 0 256 256', c: /*#__PURE__*/ svg`<path d="M136,24V232a8,8,0,0,1-16,0V24a8,8,0,0,1,16,0Z"/>` };

export default glyph;
