// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { svg } from 'lit';
import type { AltitudeIconDef } from '../types';

/** Phosphor `list` (regular). */
const glyph: AltitudeIconDef = { v: '0 0 256 256', c: /*#__PURE__*/ svg`<path d="M224,128a8,8,0,0,1-8,8H40a8,8,0,0,1,0-16H216A8,8,0,0,1,224,128ZM40,72H216a8,8,0,0,0,0-16H40a8,8,0,0,0,0,16ZM216,184H40a8,8,0,0,0,0,16H216a8,8,0,0,0,0-16Z"/>` };

export default glyph;
