// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { svg } from 'lit';
import type { AltitudeIconDef } from '../types';

/** Phosphor `lock` (regular). */
const glyph: AltitudeIconDef = { v: '0 0 256 256', c: /*#__PURE__*/ svg`<path d="M208,80H176V56a48,48,0,0,0-96,0V80H48A16,16,0,0,0,32,96V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V96A16,16,0,0,0,208,80ZM96,56a32,32,0,0,1,64,0V80H96ZM208,208H48V96H208V208Zm-68-56a12,12,0,1,1-12-12A12,12,0,0,1,140,152Z"/>` };

export default glyph;
