// AUTO-GENERATED by icons/icons-config.mjs — do not edit by hand.
import { svg } from 'lit';
import type { AltitudeIconDef } from '../types';

/** Phosphor `shopping-bag-open` (regular). */
const glyph: AltitudeIconDef = { v: '0 0 256 256', c: /*#__PURE__*/ svg`<path d="M216,40H40A16,16,0,0,0,24,56V200a16,16,0,0,0,16,16H216a16,16,0,0,0,16-16V56A16,16,0,0,0,216,40Zm0,16V72H40V56Zm0,144H40V88H216V200Zm-40-88a48,48,0,0,1-96,0,8,8,0,0,1,16,0,32,32,0,0,0,64,0,8,8,0,0,1,16,0Z"/>` };

export default glyph;
