// /tokens.json — spec 2026-08-20-southleft-example-app, T4-1.
//
// v5 served its OWN hand-parsed token snapshot (parsed from src/styles/global.css
// at build time). This app has no separate token layer: it IS an Altitude
// consumer, so the honest "design tokens this site runs on" answer is
// Altitude's own shipped contract — `al-web-components/tokens.json`
// (`libs/al-web-components/package.json` exports map, generated by
// `scripts/emit-token-types.js` from the same Style Dictionary build that
// produces the CSS this app imports). Re-served verbatim, never a copy.
import type { APIRoute } from 'astro';
import tokens from 'al-web-components/tokens.json';

export const GET: APIRoute = () =>
  new Response(JSON.stringify(tokens, null, 2), {
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  });
